"use client";

import { createContext, useContext, useEffect, useState } from "react";

export type Language = "en" | "pt" | "es";

export const LANGUAGES: { code: Language; flag: string; label: string }[] = [
  { code: "en", flag: "🇺🇸", label: "EN" },
  { code: "pt", flag: "🇧🇷", label: "PT" },
  { code: "es", flag: "🇪🇸", label: "ES" },
];

export const translations = {
  en: {
    nav: {
      build: "Build",
      the100: "The 100",
      feed: "Feed",
      membership: "Membership",
      store: "Store",
      dashboard: "Dashboard",
      haveInvite: "Have an invite?",
    },
    home: {
      eyebrow: "Brewify Coffee",
      headline: "Coffee that knows you.",
      subheadline: "One person. One blend. Only yours.",
      cta: "Build your coffee",
      alreadyHaveInvite: "Already have an invite?",
      enterCode: "Enter your code",
      inviteLabel: "Invite code",
      invitePlaceholder: "e.g. BREW-001",
      redeemBtn: "Redeem",
      redeeming: "Redeeming…",
      cancelBtn: "Cancel",
      accessGranted: "Access granted. Taking you in.",
      invalidCode: "Invalid or already redeemed.",
      somethingWrong: "Something went wrong.",
      feature1Title: "Personalized",
      feature1Desc: "Each blend is designed from your mood, rhythm, and season of life.",
      feature2Title: "Sustainable",
      feature2Desc: "Sourced with intention, roasted clean, made to be kept.",
      feature3Title: "Yours",
      feature3Desc: "No stock recipes, no generic bags. A profile that exists only for you.",
      waitlistTitle: "Join the waitlist",
      waitlistSub: "We'll notify you when the next wave opens.",
      waitlistPlaceholder: "Your email",
      waitlistBtn: "Join the waitlist",
      waitlistJoining: "Joining…",
      waitlistSuccess: "You're in. We'll notify you when the next wave opens.",
    },
    membership: {
      eyebrow: "Membership",
      headline: "Founding Access.",
      oneTime: "One-time",
      reserveTitle: "Founding Member",
      reservePrice: "$299",
      reserveSubtitle: "Founding Member — only 100 spots",
      reserveFeatures: [
        "☕ 1 free coffee per day — for life, at any store worldwide",
        "A blend built from who you are. Yours permanently.",
        "Assigned a permanent number in THE 100",
        "Your blend featured on the site forever",
        "Earn $1 per bag sold — store credit or cash at $100+",
        "3 invite tokens for people you choose",
      ],
      spotsRemaining: (n: number) => `${n} spots remaining`,
      comingSoon: "Claim your spot — $299",    },
    build: {
      header: "Blend Builder",
      stepOf: (step: number) => `Step ${step} of 6`,
      welcomeBackName: (name: string) => `Welcome back, ${name}. Let's see where your coffee wants to be today.`,
      welcomeBack: "Welcome back. Ready for another batch?",
      step1Q: "How are you feeling today?",
      step1Options: ["Focused", "Calm", "Energized", "Reflective", "Exhausted"],
      step2Q: "What are you building in your life right now?",
      step2Placeholder: "A new role. A slower rhythm. A business that feels like me...",
      step3Q: "What's your current life season?",
      step3Options: ["Starting over", "In the grind", "Finding balance", "Celebrating", "Figuring it out"],
      step4Q: "When do you reach for coffee most?",
      step4Options: ["Early morning ritual", "Midday reset", "Late-night thinker", "Whenever I need to feel like myself"],
      step5Q: "What matters most to you right now?",
      step5Options: ["Clarity", "Creativity", "Connection", "Momentum", "Rest"],
      optionalLabel: "Optional",
      labelPlaceholder: "Name for this blend on the label",
      step6Title: "Your blend, on record.",
      step6Sub: "A profile written from how you're arriving to this moment. This is your Brewify batch.",
      loadingTitle: "Designing your blend...",
      loadingSub: "Reading the small details of your day and folding them into something warm.",
      backBtn: "Back",
      nextBtn: "Next",
      designBtn: "Design My Blend",
      startAnotherBtn: "Start Another",
      profileTitle: "Your profile",
      profileDesc1: "As you move through each question, we're quietly sketching the outline of a blend that should only make sense for you.",
      profileDesc2: "When you're finished, we'll translate that into a single label: a name, a roast, and a small story about the season you're in.",
      inProgressTitle: "In progress",
      inProgressDesc: "Give us a few breaths. We're aligning the cup to the life you described.",
      addToFeedLabel: "Add to public feed?",
      instagramPlaceholder: "@instagram",
      addToFeedBtn: "Add to feed",
      addingFeed: "Adding…",
      addedFeed: "Added to public feed.",
      orderBlendBtn: "Order Your Blend",
      error: "Something went wrong while designing your blend.",
    },
    feed: {
      header: "Blend Archive",
      eyebrow: "Blend Archive",
      headline: "Every blend crafted. Each one unrepeatable.",
      loading: "Loading…",
      empty: "No blends archived yet. Be the first.",
      mostOrdered: "Most ordered",
      orderBtn: "Order this blend →",
    },
    dashboard: {
      header: "Archive",
      headline: "Your blends, in sequence.",
      subheadline: "A small record of how you've been arriving to the cup — seasons, shifts, and quiet pivots. Nothing loud, just a log.",
      roast: "Roast",
      reorderBtn: "Reorder",
      compareTitle: "Compare Blends",
    },
    store: {
      title: "GIFT STORE",
      sub: "Objects for the ritual.",
      comingSoon: "Coming soon",
      inviteTitle: "Get the opening invite.",
      inviteDesc: "Launching the store with The 100. A small first run of objects for the people building this with us.",
      emailPlaceholder: "Email",
      notifyBtn: "Notify me when the store opens",
      notifying: "Joining…",
      notifySuccess: "We'll let you know when the store opens.",
      footer: "Designed for the ritual. Launching with The 100.",
      somethingWrong: "Something went wrong.",
    },
    the100: {
      heroSub: "The founding blends of Brewify Coffee.",
      missionEyebrow: "Why it matters",
      missionTitle: "Every blend begins in the Amazon.",
      missionP1: "The coffee we source comes from small family farms deep in the Amazon basin — generations of cultivators who have spent their lives learning a single crop.",
      missionP2: "Every time a Brewify blend is ordered, a portion of that sale goes directly to the farming family whose beans made it possible. The 100 founding members carry that legacy forward.",
      missionP3: "This is not charity. It is the correct way to do business.",
      stat1Value: "10%",
      stat1Label: "of every order → farming families",
      stat2Value: "100",
      stat2Label: "founding members",
      stat3Value: "1 blend",
      stat3Label: "per person. Forever.",
      earnTitle: "You earn",
      earnP1: "Every time someone orders your blend, you earn $1.",
      earnP2: "Use it as store credit anytime, or cash it out once you hit $100.",
      impactTitle: "You impact",
      impactP1: "10% of each order of your blend goes to the farming family who grew those beans.",
      impactP2: "Your number in The 100 is a permanent contribution to their livelihood.",
      ownTitle: "You own",
      ownP1: "Your blend is an asset. Transfer it. Hold it. Let it earn.",
      ownP2: "Founding spots are limited to 100. There will never be more.",
      archiveEyebrow: "The archive",
      archiveTitle: "Claimed blends. Living on the site. Earning forever.",
      loading: "Loading…",
      spotsRemaining: (n: number) => `${n} spots remaining.`,
      ctaTitle: "Claim your number.",
      ctaSub: "One of 100 founding positions. Never restocked.",
      ctaBtn: "Get founding access — $299",
      orders: "orders",
      pts: "earned",
    },
    checkout: {
      eyebrow: "Checkout",
      title: "Coming soon — you're on the list",
      sub: (tier: string) => `We're opening ${tier} soon. You'll hear from us.`,
      back: "Back to membership",
    },
    blend: {
      eyebrow: (id: string) => `Blend ${id}`,
      title: "Order this blend",
      sub: "Checkout for pre-designed blends is coming soon.",
      back: "Back to feed",
    },
    modal: {
      amazonNote: "10% of this blend's orders support farming families in the Amazon.",
      foundingMember: "Founding member",
      crafted: "Crafted",
      blendRevenue: "Blend revenue",
      orders: "orders",
      redeemable: "Use as store credit or redeem as cash at $100+",
      pointValue: "$1 earned per bag sold",
      minRedemption: "Cash redemption available at $100+ earned",
      howEarnings: "How earnings work →",
      earningsExplain: "Every time someone orders your blend, you earn $1. Use it as store credit in the Gift Store anytime — or once you reach $100, request a cash payout directly to your account.",
      currentOwner: "Current owner",
      transferBtn: "Transfer ownership",
      transferPlaceholder: "Enter recipient's @instagram or email",
      confirm: "Confirm",
      confirming: "Transferring…",
      cancel: "Cancel",
      transferWarning: "Ownership transfers are permanent. This blend and its future earnings transfer to the new owner.",
      orderBtn: "Order this blend",
      ordering: "Ordering…",
      earnNote: "When ordered, the creator earns $1.",
      share: "Share",
      close: "Close",
    },
    footer: {
      tagline: "Brewify Coffee",
      domain: "brewifycoffee.com",
    },
  },

  pt: {
    nav: {
      build: "Criar",
      the100: "Os 100",
      feed: "Feed",
      membership: "Assinatura",
      store: "Loja",
      dashboard: "Painel",
      haveInvite: "Tem um convite?",
    },
    home: {
      eyebrow: "Brewify Coffee",
      headline: "Um café que te conhece.",
      subheadline: "Uma pessoa. Um blend. Só seu.",
      cta: "Crie seu café",
      alreadyHaveInvite: "Já tem um convite?",
      enterCode: "Digite seu código",
      inviteLabel: "Código de convite",
      invitePlaceholder: "ex: BREW-001",
      redeemBtn: "Resgatar",
      redeeming: "Resgatando…",
      cancelBtn: "Cancelar",
      accessGranted: "Acesso liberado. Te levando para dentro.",
      invalidCode: "Inválido ou já resgatado.",
      somethingWrong: "Algo deu errado.",
      feature1Title: "Personalizado",
      feature1Desc: "Cada blend é criado a partir do seu humor, ritmo e momento de vida.",
      feature2Title: "Sustentável",
      feature2Desc: "Colhido com intenção, torrado com cuidado, feito para durar.",
      feature3Title: "Seu",
      feature3Desc: "Sem receitas genéricas, sem embalagens padrão. Um perfil que existe só para você.",
      waitlistTitle: "Entre na lista de espera",
      waitlistSub: "Avisaremos quando a próxima leva abrir.",
      waitlistPlaceholder: "Seu e-mail",
      waitlistBtn: "Entrar na lista",
      waitlistJoining: "Entrando…",
      waitlistSuccess: "Você está dentro. Avisaremos quando a próxima leva abrir.",
    },
    membership: {
      eyebrow: "Assinatura",
      headline: "Acesso Fundador.",
      oneTime: "Pagamento único",
      reserveTitle: "Membro Fundador",
      reservePrice: "$299",
      reserveSubtitle: "Membro Fundador — apenas 100 vagas",
      reserveFeatures: [
        "☕ 1 café grátis por dia — para sempre, em qualquer loja no mundo",
        "Um blend criado a partir de quem você é. Seu para sempre.",
        "Número permanente atribuído em Os 100",
        "Seu blend em destaque no site para sempre",
        "Ganhe $1 por saco vendido — crédito na loja ou dinheiro a partir de $100",
        "3 tokens de convite para pessoas que você escolher",
      ],
      spotsRemaining: (n: number) => `${n} vagas restantes`,
      comingSoon: "Reserve sua vaga — $299",    },
    build: {
      header: "Criador de Blend",
      stepOf: (step: number) => `Etapa ${step} de 6`,
      welcomeBackName: (name: string) => `Bem-vindo de volta, ${name}. Vamos ver onde seu café quer chegar hoje.`,
      welcomeBack: "Bem-vindo de volta. Pronto para outro lote?",
      step1Q: "Como você está se sentindo hoje?",
      step1Options: ["Focado", "Calmo", "Energizado", "Reflexivo", "Exausto"],
      step2Q: "O que você está construindo na sua vida agora?",
      step2Placeholder: "Um novo papel. Um ritmo mais lento. Um negócio que parece a minha cara...",
      step3Q: "Em que estação da vida você está agora?",
      step3Options: ["Recomeçando", "No ritmo", "Encontrando equilíbrio", "Celebrando", "Descobrindo o caminho"],
      step4Q: "Quando você mais busca o café?",
      step4Options: ["Ritual da manhã cedo", "Pausa do meio-dia", "Pensador da madrugada", "Quando preciso me sentir eu mesmo"],
      step5Q: "O que mais importa para você agora?",
      step5Options: ["Clareza", "Criatividade", "Conexão", "Impulso", "Descanso"],
      optionalLabel: "Opcional",
      labelPlaceholder: "Nome para este blend no rótulo",
      step6Title: "Seu blend, registrado.",
      step6Sub: "Um perfil escrito a partir de como você está chegando a este momento. Este é o seu lote Brewify.",
      loadingTitle: "Criando seu blend...",
      loadingSub: "Lendo os pequenos detalhes do seu dia e transformando-os em algo especial.",
      backBtn: "Voltar",
      nextBtn: "Próximo",
      designBtn: "Criar Meu Blend",
      startAnotherBtn: "Começar Outro",
      profileTitle: "Seu perfil",
      profileDesc1: "À medida que você avança em cada pergunta, estamos desenhando silenciosamente o contorno de um blend que só faz sentido para você.",
      profileDesc2: "Quando terminar, vamos traduzir isso em um único rótulo: um nome, uma torra e uma pequena história sobre a estação em que você está.",
      inProgressTitle: "Em andamento",
      inProgressDesc: "Dê-nos alguns instantes. Estamos alinhando a xícara à vida que você descreveu.",
      addToFeedLabel: "Adicionar ao feed público?",
      instagramPlaceholder: "@instagram",
      addToFeedBtn: "Adicionar ao feed",
      addingFeed: "Adicionando…",
      addedFeed: "Adicionado ao feed público.",
      orderBlendBtn: "Pedir Seu Blend",
      error: "Algo deu errado ao criar seu blend.",
    },
    feed: {
      header: "Arquivo de Blends",
      eyebrow: "Arquivo de Blends",
      headline: "Cada blend criado. Cada um irrepetível.",
      loading: "Carregando…",
      empty: "Nenhum blend arquivado ainda. Seja o primeiro.",
      mostOrdered: "Mais pedido",
      orderBtn: "Pedir este blend →",
    },
    dashboard: {
      header: "Arquivo",
      headline: "Seus blends, em sequência.",
      subheadline: "Um pequeno registro de como você tem chegado à xícara — estações, mudanças e pivôs silenciosos. Nada barulhento, apenas um registro.",
      roast: "Torra",
      reorderBtn: "Pedir novamente",
      compareTitle: "Comparar Blends",
    },
    store: {
      title: "LOJA DE PRESENTES",
      sub: "Objetos para o ritual.",
      comingSoon: "Em breve",
      inviteTitle: "Receba o convite de abertura.",
      inviteDesc: "Lançando a loja com Os 100. Uma primeira tiragem de objetos para as pessoas que estão construindo isso conosco.",
      emailPlaceholder: "E-mail",
      notifyBtn: "Me avise quando a loja abrir",
      notifying: "Entrando…",
      notifySuccess: "Avisaremos quando a loja abrir.",
      footer: "Criado para o ritual. Lançando com Os 100.",
      somethingWrong: "Algo deu errado.",
    },
    the100: {
      heroSub: "Os blends fundadores do Brewify Coffee.",
      missionEyebrow: "Por que isso importa",
      missionTitle: "Cada blend começa na Amazônia.",
      missionP1: "O café que buscamos vem de pequenas fazendas familiares no interior da bacia Amazônica — gerações de cultivadores que dedicaram suas vidas a aprender uma única colheita.",
      missionP2: "Cada vez que um blend Brewify é pedido, uma parte dessa venda vai diretamente para a família de agricultores cujos grãos tornaram isso possível. Os 100 membros fundadores carregam esse legado adiante.",
      missionP3: "Isso não é caridade. É a forma correta de fazer negócios.",
      stat1Value: "10%",
      stat1Label: "de cada pedido → famílias agricultoras",
      stat2Value: "100",
      stat2Label: "membros fundadores",
      stat3Value: "1 blend",
      stat3Label: "por pessoa. Para sempre.",
      earnTitle: "Você ganha",
      earnP1: "Cada vez que alguém pede seu blend, você ganha $1.",
      earnP2: "Use como crédito na loja a qualquer hora, ou resgate em dinheiro ao atingir $100.",
      impactTitle: "Você impacta",
      impactP1: "10% de cada pedido do seu blend vai para a família de agricultores que cultivou esses grãos.",
      impactP2: "Seu número em Os 100 é uma contribuição permanente ao sustento deles.",
      ownTitle: "Você possui",
      ownP1: "Seu blend é um ativo. Transfira. Guarde. Deixe render.",
      ownP2: "As vagas fundadoras são limitadas a 100. Nunca haverá mais.",
      archiveEyebrow: "O arquivo",
      archiveTitle: "Blends reivindicados. Vivos no site. Rendendo para sempre.",
      loading: "Carregando…",
      spotsRemaining: (n: number) => `${n} vagas restantes.`,
      ctaTitle: "Reivindique seu número.",
      ctaSub: "Uma das 100 posições fundadoras. Nunca reabastecida.",
      ctaBtn: "Acesso fundador — $299",
      orders: "pedidos",
      pts: "ganhos",
    },
    checkout: {
      eyebrow: "Pagamento",
      title: "Em breve — você está na lista",
      sub: (tier: string) => `Estamos abrindo ${tier} em breve. Você receberá novidades.`,
      back: "Voltar para assinatura",
    },
    blend: {
      eyebrow: (id: string) => `Blend ${id}`,
      title: "Pedir este blend",
      sub: "O pagamento para blends pré-criados chegará em breve.",
      back: "Voltar para o feed",
    },
    modal: {
      amazonNote: "10% dos pedidos deste blend apoiam famílias agricultoras na Amazônia.",
      foundingMember: "Membro fundador",
      crafted: "Criado em",
      blendRevenue: "Receita do blend",
      orders: "pedidos",
      redeemable: "Use como crédito na loja ou resgate em dinheiro a partir de $100",
      pointValue: "$1 ganho por saco vendido",
      minRedemption: "Resgate em dinheiro disponível a partir de $100 ganhos",
      howEarnings: "Como os ganhos funcionam →",
      earningsExplain: "Cada vez que alguém pede seu blend, você ganha $1. Use como crédito na loja a qualquer hora — ou ao atingir $100, solicite um pagamento em dinheiro diretamente na sua conta.",
      currentOwner: "Proprietário atual",
      transferBtn: "Transferir propriedade",
      transferPlaceholder: "Digite o @instagram ou e-mail do destinatário",
      confirm: "Confirmar",
      confirming: "Transferindo…",
      cancel: "Cancelar",
      transferWarning: "As transferências de propriedade são permanentes. Este blend e seus ganhos futuros são transferidos para o novo proprietário.",
      orderBtn: "Pedir este blend",
      ordering: "Pedindo…",
      earnNote: "Quando pedido, o criador ganha $1.",
      share: "Compartilhar",
      close: "Fechar",
    },
    footer: {
      tagline: "Brewify Coffee",
      domain: "brewifycoffee.com",
    },
  },

  es: {
    nav: {
      build: "Crear",
      the100: "Los 100",
      feed: "Feed",
      membership: "Membresía",
      store: "Tienda",
      dashboard: "Panel",
      haveInvite: "¿Tienes invitación?",
    },
    home: {
      eyebrow: "Brewify Coffee",
      headline: "Un café que te conoce.",
      subheadline: "Una persona. Un blend. Solo tuyo.",
      cta: "Crea tu café",
      alreadyHaveInvite: "¿Ya tienes invitación?",
      enterCode: "Ingresa tu código",
      inviteLabel: "Código de invitación",
      invitePlaceholder: "ej: BREW-001",
      redeemBtn: "Canjear",
      redeeming: "Canjeando…",
      cancelBtn: "Cancelar",
      accessGranted: "Acceso concedido. Entrando.",
      invalidCode: "Inválido o ya canjeado.",
      somethingWrong: "Algo salió mal.",
      feature1Title: "Personalizado",
      feature1Desc: "Cada blend se diseña según tu estado de ánimo, ritmo y momento de vida.",
      feature2Title: "Sostenible",
      feature2Desc: "Cosechado con intención, tostado limpio, hecho para perdurar.",
      feature3Title: "Tuyo",
      feature3Desc: "Sin recetas genéricas, sin bolsas estándar. Un perfil que existe solo para ti.",
      waitlistTitle: "Únete a la lista de espera",
      waitlistSub: "Te avisaremos cuando abra la próxima tanda.",
      waitlistPlaceholder: "Tu correo electrónico",
      waitlistBtn: "Unirme a la lista",
      waitlistJoining: "Uniéndome…",
      waitlistSuccess: "Ya estás dentro. Te avisaremos cuando abra la próxima tanda.",
    },
    membership: {
      eyebrow: "Membresía",
      headline: "Acceso Fundador.",
      oneTime: "Pago único",
      reserveTitle: "Miembro Fundador",
      reservePrice: "$299",
      reserveSubtitle: "Miembro Fundador — solo 100 lugares",
      reserveFeatures: [
        "☕ 1 café gratis por día — de por vida, en cualquier tienda del mundo",
        "Un blend creado a partir de quién eres. Tuyo para siempre.",
        "Número permanente asignado en THE 100",
        "Tu blend destacado en el sitio para siempre",
        "Gana $1 por bolsa vendida — crédito en tienda o efectivo desde $100",
        "3 tokens de invitación para las personas que elijas",
      ],
      spotsRemaining: (n: number) => `${n} lugares restantes`,
      comingSoon: "Reserva tu lugar — $299",    },
    build: {
      header: "Creador de Blend",
      stepOf: (step: number) => `Paso ${step} de 6`,
      welcomeBackName: (name: string) => `Bienvenido de nuevo, ${name}. Veamos dónde quiere estar tu café hoy.`,
      welcomeBack: "Bienvenido de nuevo. ¿Listo para otro lote?",
      step1Q: "¿Cómo te sientes hoy?",
      step1Options: ["Enfocado", "Tranquilo", "Energizado", "Reflexivo", "Agotado"],
      step2Q: "¿Qué estás construyendo en tu vida ahora mismo?",
      step2Placeholder: "Un nuevo rol. Un ritmo más tranquilo. Un negocio que se siente como yo...",
      step3Q: "¿En qué temporada de vida estás ahora?",
      step3Options: ["Empezando de nuevo", "En la rutina", "Encontrando equilibrio", "Celebrando", "Descubriendo el camino"],
      step4Q: "¿Cuándo recurres más al café?",
      step4Options: ["Ritual de madrugada", "Pausa del mediodía", "Pensador nocturno", "Cuando necesito sentirme yo mismo"],
      step5Q: "¿Qué es lo más importante para ti ahora?",
      step5Options: ["Claridad", "Creatividad", "Conexión", "Impulso", "Descanso"],
      optionalLabel: "Opcional",
      labelPlaceholder: "Nombre para este blend en la etiqueta",
      step6Title: "Tu blend, registrado.",
      step6Sub: "Un perfil escrito desde cómo llegas a este momento. Este es tu lote Brewify.",
      loadingTitle: "Diseñando tu blend...",
      loadingSub: "Leyendo los pequeños detalles de tu día y convirtiéndolos en algo especial.",
      backBtn: "Atrás",
      nextBtn: "Siguiente",
      designBtn: "Diseñar Mi Blend",
      startAnotherBtn: "Empezar Otro",
      profileTitle: "Tu perfil",
      profileDesc1: "A medida que avanzas en cada pregunta, estamos esbozando silenciosamente el contorno de un blend que solo tiene sentido para ti.",
      profileDesc2: "Cuando termines, lo traduciremos en una sola etiqueta: un nombre, un tueste y una pequeña historia sobre la temporada en la que estás.",
      inProgressTitle: "En progreso",
      inProgressDesc: "Danos unos momentos. Estamos alineando la taza con la vida que describiste.",
      addToFeedLabel: "¿Agregar al feed público?",
      instagramPlaceholder: "@instagram",
      addToFeedBtn: "Agregar al feed",
      addingFeed: "Agregando…",
      addedFeed: "Agregado al feed público.",
      orderBlendBtn: "Pedir Tu Blend",
      error: "Algo salió mal al diseñar tu blend.",
    },
    feed: {
      header: "Archivo de Blends",
      eyebrow: "Archivo de Blends",
      headline: "Cada blend creado. Cada uno irrepetible.",
      loading: "Cargando…",
      empty: "Aún no hay blends archivados. Sé el primero.",
      mostOrdered: "Más pedido",
      orderBtn: "Pedir este blend →",
    },
    dashboard: {
      header: "Archivo",
      headline: "Tus blends, en secuencia.",
      subheadline: "Un pequeño registro de cómo has llegado a la taza — temporadas, cambios y giros silenciosos. Nada ruidoso, solo un registro.",
      roast: "Tueste",
      reorderBtn: "Volver a pedir",
      compareTitle: "Comparar Blends",
    },
    store: {
      title: "TIENDA DE REGALOS",
      sub: "Objetos para el ritual.",
      comingSoon: "Próximamente",
      inviteTitle: "Recibe la invitación de apertura.",
      inviteDesc: "Lanzando la tienda con Los 100. Una primera tirada de objetos para las personas que construyen esto con nosotros.",
      emailPlaceholder: "Correo electrónico",
      notifyBtn: "Avísame cuando abra la tienda",
      notifying: "Uniéndome…",
      notifySuccess: "Te avisaremos cuando abra la tienda.",
      footer: "Diseñado para el ritual. Lanzando con Los 100.",
      somethingWrong: "Algo salió mal.",
    },
    the100: {
      heroSub: "Los blends fundadores de Brewify Coffee.",
      missionEyebrow: "Por qué importa",
      missionTitle: "Cada blend comienza en el Amazonas.",
      missionP1: "El café que obtenemos proviene de pequeñas granjas familiares en lo profundo de la cuenca amazónica — generaciones de cultivadores que han dedicado sus vidas a aprender un solo cultivo.",
      missionP2: "Cada vez que se pide un blend Brewify, una parte de esa venta va directamente a la familia agricultora cuyos granos lo hicieron posible. Los 100 miembros fundadores llevan ese legado hacia adelante.",
      missionP3: "Esto no es caridad. Es la forma correcta de hacer negocios.",
      stat1Value: "10%",
      stat1Label: "de cada pedido → familias agricultoras",
      stat2Value: "100",
      stat2Label: "miembros fundadores",
      stat3Value: "1 blend",
      stat3Label: "por persona. Para siempre.",
      earnTitle: "Ganas",
      earnP1: "Cada vez que alguien pide tu blend, ganas $1.",
      earnP2: "Úsalo como crédito en la tienda cuando quieras, o canjéalo en efectivo al llegar a $100.",
      impactTitle: "Impactas",
      impactP1: "El 10% de cada pedido de tu blend va a la familia agricultora que cultivó esos granos.",
      impactP2: "Tu número en Los 100 es una contribución permanente a su sustento.",
      ownTitle: "Posees",
      ownP1: "Tu blend es un activo. Transfierelo. Consérvalo. Déjalo rendir.",
      ownP2: "Los lugares fundadores están limitados a 100. Nunca habrá más.",
      archiveEyebrow: "El archivo",
      archiveTitle: "Blends reclamados. Vivos en el sitio. Generando para siempre.",
      loading: "Cargando…",
      spotsRemaining: (n: number) => `${n} lugares restantes.`,
      ctaTitle: "Reclama tu número.",
      ctaSub: "Una de las 100 posiciones fundadoras. Nunca reabastecida.",
      ctaBtn: "Acceso fundador — $299",
      orders: "pedidos",
      pts: "ganados",
    },
    checkout: {
      eyebrow: "Pago",
      title: "Próximamente — ya estás en la lista",
      sub: (tier: string) => `Estamos abriendo ${tier} pronto. Te avisaremos.`,
      back: "Volver a membresía",
    },
    blend: {
      eyebrow: (id: string) => `Blend ${id}`,
      title: "Pedir este blend",
      sub: "El pago para blends prediseñados llegará pronto.",
      back: "Volver al feed",
    },
    modal: {
      amazonNote: "El 10% de los pedidos de este blend apoya a familias agricultoras en el Amazonas.",
      foundingMember: "Miembro fundador",
      crafted: "Creado el",
      blendRevenue: "Ingresos del blend",
      orders: "pedidos",
      redeemable: "Úsalo como crédito en la tienda o canjéalo en efectivo a partir de $100",
      pointValue: "$1 ganado por bolsa vendida",
      minRedemption: "Canje en efectivo disponible desde $100 ganados",
      howEarnings: "Cómo funcionan las ganancias →",
      earningsExplain: "Cada vez que alguien pide tu blend, ganas $1. Úsalo como crédito en la Tienda de Regalos cuando quieras — o cuando llegues a $100, solicita un pago en efectivo directo a tu cuenta.",
      currentOwner: "Propietario actual",
      transferBtn: "Transferir propiedad",
      transferPlaceholder: "Ingresa el @instagram o correo del destinatario",
      confirm: "Confirmar",
      confirming: "Transfiriendo…",
      cancel: "Cancelar",
      transferWarning: "Las transferencias de propiedad son permanentes. Este blend y sus ganancias futuras se transfieren al nuevo propietario.",
      orderBtn: "Pedir este blend",
      ordering: "Pidiendo…",
      earnNote: "Cuando se pide, el creador gana $1.",
      share: "Compartir",
      close: "Cerrar",
    },
    footer: {
      tagline: "Brewify Coffee",
      domain: "brewifycoffee.com",
    },
  },
} as const;

// ─── Extended translations (new pages) ────────────────────────────────────────
export const extTranslations = {
  en: {
    footer: {
      tagline: "The world's first fully personalized coffee.",
      explore: "Explore",
      company: "Company",
      legal: "Legal",
      links: {
        explore: [
          { label: "The 100", href: "/the-100" },
          { label: "Build Your Coffee", href: "/build" },
          { label: "Blend Feed", href: "/feed" },
          { label: "Gift Store", href: "/store" },
          { label: "Membership", href: "/membership" },
        ],
        company: [
          { label: "Our Coffee", href: "/our-coffee" },
          { label: "Investor Relations", href: "/investor" },
          { label: "Contact", href: "/contact" },
        ],
        legal: [
          { label: "Privacy Policy", href: "/privacy" },
          { label: "Terms of Use", href: "/terms" },
          { label: "Accessibility", href: "/accessibility" },
          { label: "Do Not Sell My Info", href: "/do-not-sell" },
        ],
      },
      igLabel: "@brewifycoffee",
      ttLabel: "@brewifycoffee",
      copyright: (year: number) => `© ${year} Brewify Coffee. All rights reserved.`,
    },
    contact: {
      eyebrow: "Contact",
      headline: "Let's talk.",
      sub: "Whether you have a question about your blend, want to learn more about THE 100, or just want to say hello — we read every message.",
      emailLabel: "Email us directly",
      responseLabel: "Response time",
      responseValue: "Within 24 hours, usually sooner.",
      nameLabel: "Name",
      emailField: "Email",
      subjectLabel: "Subject",
      messageLabel: "Message",
      namePlaceholder: "Your name",
      emailPlaceholder: "you@example.com",
      messagePlaceholder: "Tell us what's on your mind...",
      subjectOptions: ["Select a topic", "My Blend", "THE 100 Membership", "Gift Store", "Investor Inquiry", "Press & Media", "Partnership", "Other"],
      sendBtn: "Send message",
      sending: "Sending…",
      successTitle: "Message sent.",
      successSub: (email: string) => `We'll be in touch at ${email} within 24 hours.`,
      sendAnother: "Send another",
      replyNote: "We'll reply to iam@brewifycoffee.com within 24 hours.",
      errorFallback: "Something went wrong. Please try again.",
    },
    ourCoffee: {
      eyebrow: "Our Coffee",
      headline: "The world's first fully\npersonalized coffee.",
      subheadline: "Not a subscription. Not a quiz with preset results. A blend designed from who you actually are — never repeated, never shared.",
      uniqueEyebrow: "What makes it different",
      uniqueHeadline: "Every other coffee brand sells you a product.\nWe build you one.",
      uniqueP1: 'Most "personalized" coffee sends you a quiz and picks from 5 existing blends. Brewify does something nobody else does: it starts from zero, reads how you\'re showing up to life right now, and designs a blend that only makes sense for you.',
      uniqueP2: "The result has a name, a roast, a flavor profile, and a story — written in the language of your moment. And once it's created, it's yours. Permanently. On the site. Earning every time someone orders it.",
      processEyebrow: "The process",
      processHeadline: "From your answers to your cup.",
      steps: [
        { n: "01", title: "You answer 5 questions", body: "Mood. Life season. When you drink it. What you're building. What matters. Simple, honest, fast." },
        { n: "02", title: "We design your blend", body: "Our model translates your answers into a roast level, flavor profile, and a small story — written only about you." },
        { n: "03", title: "It becomes yours", body: "Your blend gets a name, a label, and a permanent place on the site. Nobody else will ever have the same one." },
        { n: "04", title: "You earn from it", body: "Every time someone orders your blend, you earn $1. Use it as store credit or cash out at $100+." },
      ],
      farmerEyebrow: "The source",
      farmerHeadline: "Every blend starts in the hands of a farming family.",
      farmerP1: "Our beans come from small family farms in the Amazon basin — cultivators who have spent generations mastering a single crop. Not industrial estates. Not mass commodity supply chains.",
      farmerP2: "When you order a Brewify blend, 10% of that sale goes directly to the farming family whose beans made it. Not as charity. As a fair share of the value they created.",
      farmerP3: "THE 100 founding members carry that commitment forward permanently — their blends earn income for farmers every time they're ordered.",
      farmerLocation: "Amazon basin · Brazil",
      valuesEyebrow: "What we stand for",
      valuesHeadline: "Built differently. On purpose.",
      values: [
        { icon: "🌱", title: "Amazon-sourced", body: "Every bean comes from small family farms deep in the Amazon basin. People who've spent generations learning a single crop." },
        { icon: "💰", title: "Direct earnings for farmers", body: "10% of every order goes directly to the farming family whose beans made it possible. Not a donation — a fair share of the sale." },
        { icon: "♻️", title: "Roasted clean", body: "Small-batch roasting on demand. No over-production, no warehoused stock going stale. Your bag is roasted when you order it." },
        { icon: "🔒", title: "No generic recipes", body: "We don't have a catalog. Every blend is built from scratch, for one person. Nothing is repeated." },
      ],
      ctaHeadline: "Ready to build yours?",
      ctaSub: "Become a founding member of THE 100 and be part of how Brewify starts.",
      ctaPrimary: "Claim your spot — $299",
      ctaSecondary: "Explore THE 100",
    },
    investor: {
      eyebrow: "Investor Relations",
      headline: "The coffee industry\nhasn't changed.",
      headlineItalic: "We're changing it.",
      subheadline: "Brewify is building the first coffee brand where every product is unique, every customer is a creator, and every order supports the people who grow the beans.",
      cta: "Request a conversation",
      metrics: [
        { value: "$200B+", label: "Global coffee market", sub: "One of the largest daily-habit consumer categories on earth." },
        { value: "0", label: "True personalization players", sub: "No brand has solved per-person coffee at scale. The category is wide open." },
        { value: "94%", label: "Retention via identity", sub: "Products tied to personal identity retain customers at rates mass brands can't reach." },
        { value: "3×", label: "LTV vs commodity coffee", sub: "Personalized products command higher margins and longer customer relationships." },
      ],
      opportunityEyebrow: "The opportunity",
      opportunityHeadline: "Six reasons the timing is right.",
      why: [
        { title: "Category gap", body: "No brand has combined AI-personalized coffee, a creator economy layer, and Amazon-farmer direct sourcing into a single product. Brewify sits at the intersection of all three." },
        { title: "Recurring by design", body: "Once someone builds their blend, they reorder it. The personal connection to a named, authored product creates retention that commodity subscriptions can't match." },
        { title: "Asset-based loyalty", body: "THE 100 members don't just subscribe — they own something. A blend that earns them money. That's a fundamentally different relationship with a brand." },
        { title: "Ethical moat", body: "The Amazon sourcing model and direct farmer payments aren't marketing copy — they're structural. Hard to copy. Easy to tell." },
        { title: "Digital-physical bridge", body: "Every blend lives online permanently. It can be gifted, transferred, ordered by anyone. It's a physical product with digital asset mechanics." },
        { title: "Early traction model", body: "The 100 founding members prove demand, fund the initial roasting operations, and create the community that markets the product organically." },
      ],
      visionEyebrow: "The vision",
      visionHeadline: "Phase one is coffee.\nPhase two is everything you personalize.",
      visionP1: "Brewify's core technology is a personalization engine that translates human context — mood, season of life, aspiration — into a physical product. Coffee is the first application because it's intimate, daily, and deeply tied to identity.",
      visionP2: "The longer-term thesis is a platform: any product category where personal context changes what someone would want. Tea. Supplements. Fragrance. The infrastructure being built for coffee applies everywhere.",
      visionP3: "We're not selling bags of coffee. We're building infrastructure for personalized physical goods — starting where the emotional attachment is deepest.",
      contactEyebrow: "Get in touch",
      contactHeadline: "Interested in investing?",
      contactSub: "We're having early conversations with investors who understand brand, community, and the consumer goods space. If that's you, we'd like to talk.",
      contactEmailLabel: "Direct email",
      nameLabel: "Name",
      emailLabel: "Email",
      firmLabel: "Firm / Organization",
      firmOptional: "(optional)",
      firmPlaceholder: "Fund name or company",
      namePlaceholder: "Your name",
      emailPlaceholder: "you@firm.com",
      messagePlaceholder: "Tell us about your investment thesis and what draws you to Brewify...",
      messageLabel: "Message",
      sendBtn: "Send inquiry",
      sending: "Sending…",
      successTitle: "Message received.",
      successSub: "We'll follow up within 48 hours.",
      responseNote: "We respond to all serious inquiries within 48 hours.",
    },
    terms: {
      eyebrow: "Legal",
      headline: "Terms of Use",
      updated: "Last updated: March 2026",
      sections: [
        { title: "1. Acceptance of Terms", body: "By accessing or using Brewify Coffee (Brewify, we, us), you agree to be bound by these Terms of Use. If you do not agree, please do not use the site or services." },
        { title: "2. Use of the Site", body: "You may browse Brewify for personal, non-commercial purposes. You agree not to copy, scrape, resell, or exploit any content or functionality of the platform without written permission." },
        { title: "3. Accounts and Access", body: "Certain features — including Build Your Coffee and THE 100 membership — require an account or verified invite code. You are responsible for maintaining the confidentiality of your credentials." },
        { title: "4. THE 100 Membership", body: "Purchasing a founding membership grants you the rights described on the Membership page, including a permanent blend slot, earnings on orders of your blend, and invite tokens. These rights are non-refundable once your blend is created. Blend ownership may be transferred to another user." },
        { title: "5. Earnings and Payouts", body: "Members earn $1 per bag sold of their blend. Earnings may be applied as store credit at any time. Cash payouts require a minimum balance of $100 and are processed on a monthly basis upon request." },
        { title: "6. Intellectual Property", body: "Blend names, stories, and profiles created through Brewify are associated with your account but may appear publicly on the site. Brewify retains the right to display your blend as part of the platform." },
        { title: "7. Prohibited Conduct", body: "You agree not to: use the platform for any unlawful purpose; attempt to gain unauthorized access to any part of the site; submit false or misleading information; or interfere with the security of the platform." },
        { title: "8. Limitation of Liability", body: "Brewify is provided as-is. We are not liable for any indirect, incidental, or consequential damages arising from your use of the platform, to the maximum extent permitted by law." },
        { title: "9. Changes to Terms", body: "We may update these Terms at any time. Continued use of the site after changes constitutes acceptance of the revised Terms." },
        { title: "10. Contact", body: "Questions about these Terms? Email us at iam@brewifycoffee.com." },
      ],
    },
    privacy: {
      eyebrow: "Legal",
      headline: "Privacy Policy",
      updated: "Last updated: March 2026",
      sections: [
        { title: "1. Information We Collect", body: "We collect information you provide directly — such as your name, email address, and responses to blend-building questions — as well as technical data like IP address, browser type, and pages visited." },
        { title: "2. How We Use Your Information", body: "We use your information to create and deliver your personalized blend, manage your account, send transactional emails, process earnings and payouts, and improve the platform. We do not sell your personal information to third parties." },
        { title: "3. Blend Data", body: "Your blend profile — including your answers, blend name, roast level, and flavor notes — may be displayed publicly on the site if you choose to add your blend to the public feed. You can opt out during the build process." },
        { title: "4. Cookies", body: "We use essential cookies to maintain your session and preferences (such as language selection). We do not use tracking or advertising cookies." },
        { title: "5. Data Retention", body: "We retain your account data for as long as your account is active or as needed to provide services. You may request deletion of your data at any time by contacting us." },
        { title: "6. Third-Party Services", body: "We use Vercel for hosting. Your data may be processed on servers in the United States. We do not share your personal data with advertising networks or data brokers." },
        { title: "7. Your Rights", body: "Depending on your location, you may have the right to access, correct, delete, or restrict the processing of your personal data. To exercise these rights, contact us at iam@brewifycoffee.com." },
        { title: "8. Children", body: "Brewify is not directed at children under 13. We do not knowingly collect data from children under 13." },
        { title: "9. Changes to This Policy", body: "We may update this Privacy Policy periodically. We will notify registered users of material changes by email." },
        { title: "10. Contact", body: "Questions about privacy? Email us at iam@brewifycoffee.com." },
      ],
    },
    accessibility: {
      eyebrow: "Legal",
      headline: "Accessibility Statement",
      updated: "Last updated: March 2026",
      commitmentTitle: "Our Commitment",
      commitmentBody: "Brewify Coffee is committed to making our website accessible to all users, regardless of ability or technology. We strive to conform to the Web Content Accessibility Guidelines (WCAG) 2.1, Level AA.",
      measuresTitle: "Measures We Take",
      measures: [
        "Semantic HTML for clear document structure",
        "Sufficient color contrast ratios across all text elements",
        "Keyboard navigability throughout the site",
        "Descriptive alt text on all meaningful images",
        "Clear focus indicators for keyboard users",
        "Responsive design that works across screen sizes and zoom levels",
        "Forms with clearly labeled fields and accessible error messages",
      ],
      limitationsTitle: "Known Limitations",
      limitationsBody: "While we strive for full accessibility, some elements may not yet meet all WCAG 2.1 AA criteria. We are actively working to identify and resolve these gaps.",
      feedbackTitle: "Feedback & Contact",
      feedbackBody: "If you experience any accessibility barrier or have feedback, please contact us:",
      responseNote: "We aim to respond to accessibility feedback within 3 business days.",
    },
    doNotSell: {
      eyebrow: "Legal",
      headline: "Do Not Sell or Share My Personal Information",
      subtitle: "In accordance with the California Consumer Privacy Act (CCPA) and similar regulations.",
      commitmentTitle: "Our Commitment",
      commitmentP1: "Brewify Coffee does not sell your personal information to third parties and does not share it with third parties for cross-context behavioral advertising.",
      commitmentP2: "We collect only what is necessary to operate the platform — your email, blend preferences, and account activity. This information is used solely to provide our service to you.",
      rightsTitle: "Your Rights (CCPA & Similar Laws)",
      rights: [
        "Know what personal information we collect and how it's used",
        "Request deletion of your personal information",
        "Opt out of the sale or sharing of your personal information",
        "Non-discrimination for exercising your privacy rights",
      ],
      optOutTitle: "Submit an Opt-Out Request",
      optOutSub: "Enter your email address below to formally request that we do not sell or share your personal information.",
      emailPlaceholder: "your@email.com",
      submitBtn: "Submit opt-out request",
      successTitle: "Request received.",
      successSub: "We will process your request within 15 business days.",
      contactTitle: "Contact",
      contactBody: "For privacy-related requests, you may also email us directly at",
    },
  },

  pt: {
    footer: {
      tagline: "O primeiro café totalmente personalizado do mundo.",
      explore: "Explorar",
      company: "Empresa",
      legal: "Legal",
      links: {
        explore: [
          { label: "Os 100", href: "/the-100" },
          { label: "Crie seu Café", href: "/build" },
          { label: "Feed de Blends", href: "/feed" },
          { label: "Loja de Presentes", href: "/store" },
          { label: "Assinatura", href: "/membership" },
        ],
        company: [
          { label: "Nosso Café", href: "/our-coffee" },
          { label: "Relações com Investidores", href: "/investor" },
          { label: "Contato", href: "/contact" },
        ],
        legal: [
          { label: "Política de Privacidade", href: "/privacy" },
          { label: "Termos de Uso", href: "/terms" },
          { label: "Acessibilidade", href: "/accessibility" },
          { label: "Não Vender Meus Dados", href: "/do-not-sell" },
        ],
      },
      igLabel: "@brewifycoffee",
      ttLabel: "@brewifycoffee",
      copyright: (year: number) => `© ${year} Brewify Coffee. Todos os direitos reservados.`,
    },
    contact: {
      eyebrow: "Contato",
      headline: "Vamos conversar.",
      sub: "Seja uma dúvida sobre seu blend, interesse em Os 100 ou apenas um olá — lemos todas as mensagens.",
      emailLabel: "Fale diretamente por e-mail",
      responseLabel: "Tempo de resposta",
      responseValue: "Dentro de 24 horas, geralmente antes.",
      nameLabel: "Nome",
      emailField: "E-mail",
      subjectLabel: "Assunto",
      messageLabel: "Mensagem",
      namePlaceholder: "Seu nome",
      emailPlaceholder: "voce@exemplo.com",
      messagePlaceholder: "Nos conte o que está pensando...",
      subjectOptions: ["Selecione um assunto", "Meu Blend", "Assinatura Os 100", "Loja de Presentes", "Consulta de Investimento", "Imprensa e Mídia", "Parceria", "Outro"],
      sendBtn: "Enviar mensagem",
      sending: "Enviando…",
      successTitle: "Mensagem enviada.",
      successSub: (email: string) => `Entraremos em contato em ${email} em até 24 horas.`,
      sendAnother: "Enviar outra",
      replyNote: "Responderemos via iam@brewifycoffee.com em até 24 horas.",
      errorFallback: "Algo deu errado. Tente novamente.",
    },
    ourCoffee: {
      eyebrow: "Nosso Café",
      headline: "O primeiro café totalmente\npersonalizado do mundo.",
      subheadline: "Não é uma assinatura. Não é um quiz com resultados pré-definidos. Um blend desenhado a partir de quem você realmente é — nunca repetido, nunca compartilhado.",
      uniqueEyebrow: "O que faz a diferença",
      uniqueHeadline: "Toda outra marca de café vende um produto.\nNós criamos um para você.",
      uniqueP1: 'A maioria dos cafés "personalizados" oferece um quiz e escolhe entre 5 blends existentes. Brewify faz algo que ninguém mais faz: começa do zero, lê como você está chegando à vida neste momento, e cria um blend que só faz sentido para você.',
      uniqueP2: "O resultado tem um nome, uma torra, um perfil de sabor e uma história — escrita na linguagem do seu momento. E uma vez criado, é seu. Permanentemente. No site. Rendendo cada vez que alguém pedir.",
      processEyebrow: "O processo",
      processHeadline: "Das suas respostas à sua xícara.",
      steps: [
        { n: "01", title: "Você responde 5 perguntas", body: "Humor. Estação de vida. Quando você bebe. O que está construindo. O que importa. Simples, honesto, rápido." },
        { n: "02", title: "Criamos seu blend", body: "Nosso modelo traduz suas respostas em nível de torra, perfil de sabor e uma pequena história — escrita só para você." },
        { n: "03", title: "Ele se torna seu", body: "Seu blend recebe um nome, um rótulo e um lugar permanente no site. Ninguém mais terá o mesmo." },
        { n: "04", title: "Você ganha com ele", body: "Cada vez que alguém pedir seu blend, você ganha $1. Use como crédito na loja ou resgate em dinheiro a partir de $100." },
      ],
      farmerEyebrow: "A origem",
      farmerHeadline: "Cada blend começa nas mãos de uma família de agricultores.",
      farmerP1: "Nossos grãos vêm de pequenas fazendas familiares na bacia Amazônica — cultivadores que passaram gerações dominando uma única colheita. Não são grandes propriedades industriais. Não são cadeias de suprimento de commodities.",
      farmerP2: "Quando você pede um blend Brewify, 10% dessa venda vai diretamente para a família de agricultores cujos grãos tornaram isso possível. Não como caridade. Como uma parte justa do valor que eles criaram.",
      farmerP3: "Os 100 membros fundadores carregam esse compromisso para sempre — seus blends geram renda para os agricultores toda vez que são pedidos.",
      farmerLocation: "Bacia Amazônica · Brasil",
      valuesEyebrow: "O que defendemos",
      valuesHeadline: "Construído de forma diferente. Com propósito.",
      values: [
        { icon: "🌱", title: "Origem Amazônica", body: "Cada grão vem de pequenas fazendas familiares no interior da Amazônia. Pessoas que passaram gerações aprendendo uma única colheita." },
        { icon: "💰", title: "Ganhos diretos para agricultores", body: "10% de cada pedido vai diretamente para a família de agricultores que tornou isso possível. Não é doação — é uma parte justa da venda." },
        { icon: "♻️", title: "Torrado limpo", body: "Torra em pequenos lotes sob demanda. Sem superprodução, sem estoque envelhecendo. Seu saco é torrado quando você pede." },
        { icon: "🔒", title: "Sem receitas genéricas", body: "Não temos catálogo. Cada blend é criado do zero, para uma pessoa. Nada é repetido." },
      ],
      ctaHeadline: "Pronto para criar o seu?",
      ctaSub: "Torne-se membro fundador de Os 100 e faça parte do início do Brewify.",
      ctaPrimary: "Reserve seu lugar — $299",
      ctaSecondary: "Explorar Os 100",
    },
    investor: {
      eyebrow: "Relações com Investidores",
      headline: "O setor de café\nnão mudou.",
      headlineItalic: "Estamos mudando.",
      subheadline: "Brewify está construindo a primeira marca de café onde cada produto é único, cada cliente é um criador, e cada pedido apoia quem cultiva os grãos.",
      cta: "Solicitar uma conversa",
      metrics: [
        { value: "$200B+", label: "Mercado global de café", sub: "Uma das maiores categorias de consumo diário do mundo." },
        { value: "0", label: "Concorrentes em personalização real", sub: "Nenhuma marca resolveu café por pessoa em escala. A categoria está completamente aberta." },
        { value: "94%", label: "Retenção por identidade", sub: "Produtos ligados à identidade pessoal retêm clientes em taxas que marcas genéricas não alcançam." },
        { value: "3×", label: "LTV vs café commodity", sub: "Produtos personalizados têm margens maiores e relacionamentos mais longos com clientes." },
      ],
      opportunityEyebrow: "A oportunidade",
      opportunityHeadline: "Seis razões para o momento ser agora.",
      why: [
        { title: "Lacuna no mercado", body: "Nenhuma marca combinou café personalizado por IA, uma camada de economia criativa e fornecimento direto de agricultores amazônicos em um único produto." },
        { title: "Recorrência por design", body: "Uma vez que alguém cria seu blend, ele reordena. A conexão pessoal com um produto nomeado e autoral cria retenção que assinaturas genéricas não conseguem." },
        { title: "Lealdade baseada em ativos", body: "Os 100 membros não apenas assinam — eles possuem algo. Um blend que gera dinheiro para eles. Isso é um relacionamento fundamentalmente diferente com uma marca." },
        { title: "Vantagem ética", body: "O modelo de fornecimento amazônico e os pagamentos diretos aos agricultores não são texto de marketing — são estruturais. Difícil de copiar. Fácil de contar." },
        { title: "Ponte digital-física", body: "Cada blend vive online permanentemente. Pode ser presenteado, transferido, pedido por qualquer pessoa. É um produto físico com mecânicas de ativo digital." },
        { title: "Modelo de tração inicial", body: "Os 100 membros fundadores provam a demanda, financiam as operações iniciais de torra e criam a comunidade que comercializa o produto organicamente." },
      ],
      visionEyebrow: "A visão",
      visionHeadline: "A fase um é café.\nA fase dois é tudo que você personaliza.",
      visionP1: "A tecnologia central do Brewify é um motor de personalização que traduz contexto humano — humor, estação de vida, aspiração — em um produto físico. O café é a primeira aplicação porque é íntimo, diário e profundamente ligado à identidade.",
      visionP2: "A tese de longo prazo é uma plataforma: qualquer categoria de produto onde o contexto pessoal muda o que alguém quer. Chá. Suplementos. Fragrância. A infraestrutura construída para o café se aplica em todos os lugares.",
      visionP3: "Não estamos vendendo sacos de café. Estamos construindo infraestrutura para bens físicos personalizados — começando onde o apego emocional é mais profundo.",
      contactEyebrow: "Entre em contato",
      contactHeadline: "Interessado em investir?",
      contactSub: "Estamos tendo conversas iniciais com investidores que entendem marca, comunidade e o espaço de bens de consumo. Se for você, gostaríamos de conversar.",
      contactEmailLabel: "E-mail direto",
      nameLabel: "Nome",
      emailLabel: "E-mail",
      firmLabel: "Empresa / Organização",
      firmOptional: "(opcional)",
      firmPlaceholder: "Nome do fundo ou empresa",
      namePlaceholder: "Seu nome",
      emailPlaceholder: "voce@empresa.com",
      messagePlaceholder: "Conte-nos sobre sua tese de investimento e o que te atrai no Brewify...",
      messageLabel: "Mensagem",
      sendBtn: "Enviar consulta",
      sending: "Enviando…",
      successTitle: "Mensagem recebida.",
      successSub: "Entraremos em contato em até 48 horas.",
      responseNote: "Respondemos a todas as consultas sérias em até 48 horas.",
    },
    terms: {
      eyebrow: "Legal",
      headline: "Termos de Uso",
      updated: "Última atualização: março de 2026",
      sections: [
        { title: "1. Aceitação dos Termos", body: "Ao acessar ou usar o Brewify Coffee (Brewify, nós), você concorda em cumprir estes Termos de Uso. Se não concordar, por favor não use o site ou os serviços." },
        { title: "2. Uso do Site", body: "Você pode navegar pelo Brewify para fins pessoais e não comerciais. Você concorda em não copiar, raspar, revender ou explorar qualquer conteúdo ou funcionalidade da plataforma sem permissão por escrito." },
        { title: "3. Contas e Acesso", body: "Alguns recursos — incluindo Crie seu Café e a assinatura Os 100 — exigem uma conta ou código de convite verificado. Você é responsável por manter a confidencialidade de suas credenciais." },
        { title: "4. Assinatura Os 100", body: "A compra de uma assinatura fundadora concede os direitos descritos na página de Assinatura, incluindo um slot permanente de blend, ganhos sobre pedidos do seu blend e tokens de convite. Esses direitos não são reembolsáveis após a criação do blend. A propriedade do blend pode ser transferida para outro usuário." },
        { title: "5. Ganhos e Pagamentos", body: "Os membros ganham $1 por saco vendido do seu blend. Os ganhos podem ser usados como crédito na loja a qualquer momento. Pagamentos em dinheiro exigem saldo mínimo de $100 e são processados mensalmente mediante solicitação." },
        { title: "6. Propriedade Intelectual", body: "Nomes de blends, histórias e perfis criados através do Brewify estão associados à sua conta, mas podem aparecer publicamente no site. O Brewify mantém o direito de exibir seu blend como parte da plataforma." },
        { title: "7. Conduta Proibida", body: "Você concorda em não: usar a plataforma para qualquer finalidade ilegal; tentar acesso não autorizado a qualquer parte do site; enviar informações falsas ou enganosas; ou interferir na segurança da plataforma." },
        { title: "8. Limitação de Responsabilidade", body: "O Brewify é fornecido como está. Não somos responsáveis por quaisquer danos indiretos, incidentais ou consequenciais decorrentes do uso da plataforma, na extensão máxima permitida por lei." },
        { title: "9. Alterações nos Termos", body: "Podemos atualizar estes Termos a qualquer momento. O uso continuado do site após as alterações constitui aceitação dos Termos revisados." },
        { title: "10. Contato", body: "Dúvidas sobre estes Termos? Envie-nos um e-mail para iam@brewifycoffee.com." },
      ],
    },
    privacy: {
      eyebrow: "Legal",
      headline: "Política de Privacidade",
      updated: "Última atualização: março de 2026",
      sections: [
        { title: "1. Informações que Coletamos", body: "Coletamos informações que você fornece diretamente — como nome, endereço de e-mail e respostas às perguntas de criação de blend — bem como dados técnicos como endereço IP, tipo de navegador e páginas visitadas." },
        { title: "2. Como Usamos Suas Informações", body: "Usamos suas informações para criar e entregar seu blend personalizado, gerenciar sua conta, enviar e-mails transacionais, processar ganhos e pagamentos e melhorar a plataforma. Não vendemos suas informações pessoais a terceiros." },
        { title: "3. Dados do Blend", body: "Seu perfil de blend — incluindo respostas, nome do blend, nível de torra e notas de sabor — pode ser exibido publicamente no site se você optar por adicionar seu blend ao feed público. Você pode recusar durante o processo de criação." },
        { title: "4. Cookies", body: "Usamos cookies essenciais para manter sua sessão e preferências (como seleção de idioma). Não usamos cookies de rastreamento ou publicidade." },
        { title: "5. Retenção de Dados", body: "Retemos seus dados enquanto sua conta estiver ativa ou conforme necessário para fornecer serviços. Você pode solicitar a exclusão de seus dados a qualquer momento entrando em contato conosco." },
        { title: "6. Serviços de Terceiros", body: "Usamos a Vercel para hospedagem. Seus dados podem ser processados em servidores nos Estados Unidos. Não compartilhamos seus dados pessoais com redes de publicidade ou corretores de dados." },
        { title: "7. Seus Direitos", body: "Dependendo de sua localização, você pode ter o direito de acessar, corrigir, excluir ou restringir o processamento de seus dados pessoais. Para exercer esses direitos, entre em contato via iam@brewifycoffee.com." },
        { title: "8. Crianças", body: "O Brewify não é direcionado a crianças menores de 13 anos. Não coletamos dados de crianças menores de 13 anos de forma intencional." },
        { title: "9. Alterações nesta Política", body: "Podemos atualizar esta Política de Privacidade periodicamente. Notificaremos usuários registrados sobre alterações relevantes por e-mail." },
        { title: "10. Contato", body: "Dúvidas sobre privacidade? Envie-nos um e-mail para iam@brewifycoffee.com." },
      ],
    },
    accessibility: {
      eyebrow: "Legal",
      headline: "Declaração de Acessibilidade",
      updated: "Última atualização: março de 2026",
      commitmentTitle: "Nosso Compromisso",
      commitmentBody: "O Brewify Coffee está comprometido em tornar nosso site acessível a todos os usuários, independentemente de capacidade ou tecnologia. Buscamos conformidade com as Diretrizes de Acessibilidade para Conteúdo Web (WCAG) 2.1, Nível AA.",
      measuresTitle: "Medidas que Tomamos",
      measures: [
        "HTML semântico para estrutura clara do documento",
        "Taxas de contraste de cor adequadas em todos os elementos de texto",
        "Navegabilidade por teclado em todo o site",
        "Texto alternativo descritivo em todas as imagens significativas",
        "Indicadores de foco claros para usuários de teclado",
        "Design responsivo para diferentes tamanhos de tela e níveis de zoom",
        "Formulários com campos claramente rotulados e mensagens de erro acessíveis",
      ],
      limitationsTitle: "Limitações Conhecidas",
      limitationsBody: "Embora busquemos acessibilidade plena, alguns elementos podem ainda não atender a todos os critérios WCAG 2.1 AA. Estamos trabalhando ativamente para identificar e resolver essas lacunas.",
      feedbackTitle: "Feedback e Contato",
      feedbackBody: "Se você encontrar alguma barreira de acessibilidade ou tiver sugestões, entre em contato conosco:",
      responseNote: "Buscamos responder ao feedback de acessibilidade em até 3 dias úteis.",
    },
    doNotSell: {
      eyebrow: "Legal",
      headline: "Não Venda ou Compartilhe Minhas Informações Pessoais",
      subtitle: "Em conformidade com a Lei de Privacidade do Consumidor da Califórnia (CCPA) e regulamentos similares.",
      commitmentTitle: "Nosso Compromisso",
      commitmentP1: "O Brewify Coffee não vende suas informações pessoais a terceiros e não as compartilha com terceiros para publicidade comportamental entre contextos.",
      commitmentP2: "Coletamos apenas o necessário para operar a plataforma — seu e-mail, preferências de blend e atividade na conta. Essas informações são usadas exclusivamente para fornecer nosso serviço a você.",
      rightsTitle: "Seus Direitos (CCPA e Leis Similares)",
      rights: [
        "Saber quais informações pessoais coletamos e como são usadas",
        "Solicitar a exclusão de suas informações pessoais",
        "Optar por não vender ou compartilhar suas informações pessoais",
        "Não sofrer discriminação por exercer seus direitos de privacidade",
      ],
      optOutTitle: "Enviar Solicitação de Exclusão",
      optOutSub: "Insira seu endereço de e-mail abaixo para solicitar formalmente que não vendamos ou compartilhemos suas informações pessoais.",
      emailPlaceholder: "seu@email.com",
      submitBtn: "Enviar solicitação de exclusão",
      successTitle: "Solicitação recebida.",
      successSub: "Processaremos sua solicitação em até 15 dias úteis.",
      contactTitle: "Contato",
      contactBody: "Para solicitações relacionadas à privacidade, você também pode nos enviar um e-mail diretamente em",
    },
  },

  es: {
    footer: {
      tagline: "El primer café totalmente personalizado del mundo.",
      explore: "Explorar",
      company: "Empresa",
      legal: "Legal",
      links: {
        explore: [
          { label: "Los 100", href: "/the-100" },
          { label: "Crea tu Café", href: "/build" },
          { label: "Feed de Blends", href: "/feed" },
          { label: "Tienda de Regalos", href: "/store" },
          { label: "Membresía", href: "/membership" },
        ],
        company: [
          { label: "Nuestro Café", href: "/our-coffee" },
          { label: "Relaciones con Inversores", href: "/investor" },
          { label: "Contacto", href: "/contact" },
        ],
        legal: [
          { label: "Política de Privacidad", href: "/privacy" },
          { label: "Términos de Uso", href: "/terms" },
          { label: "Accesibilidad", href: "/accessibility" },
          { label: "No Vender Mis Datos", href: "/do-not-sell" },
        ],
      },
      igLabel: "@brewifycoffee",
      ttLabel: "@brewifycoffee",
      copyright: (year: number) => `© ${year} Brewify Coffee. Todos los derechos reservados.`,
    },
    contact: {
      eyebrow: "Contacto",
      headline: "Hablemos.",
      sub: "Tengas una pregunta sobre tu blend, quieras saber más sobre THE 100 o simplemente quieras saludar — leemos cada mensaje.",
      emailLabel: "Escríbenos directamente",
      responseLabel: "Tiempo de respuesta",
      responseValue: "Dentro de 24 horas, generalmente antes.",
      nameLabel: "Nombre",
      emailField: "Correo electrónico",
      subjectLabel: "Asunto",
      messageLabel: "Mensaje",
      namePlaceholder: "Tu nombre",
      emailPlaceholder: "tu@ejemplo.com",
      messagePlaceholder: "Cuéntanos qué tienes en mente...",
      subjectOptions: ["Selecciona un tema", "Mi Blend", "Membresía THE 100", "Tienda de Regalos", "Consulta de Inversión", "Prensa y Medios", "Alianza", "Otro"],
      sendBtn: "Enviar mensaje",
      sending: "Enviando…",
      successTitle: "Mensaje enviado.",
      successSub: (email: string) => `Nos pondremos en contacto en ${email} dentro de 24 horas.`,
      sendAnother: "Enviar otro",
      replyNote: "Responderemos desde iam@brewifycoffee.com en 24 horas.",
      errorFallback: "Algo salió mal. Por favor intenta de nuevo.",
    },
    ourCoffee: {
      eyebrow: "Nuestro Café",
      headline: "El primer café totalmente\npersonalizado del mundo.",
      subheadline: "No es una suscripción. No es un cuestionario con resultados preestablecidos. Un blend diseñado a partir de quién eres realmente — nunca repetido, nunca compartido.",
      uniqueEyebrow: "Lo que lo hace diferente",
      uniqueHeadline: "Cada otra marca de café te vende un producto.\nNosotros te creamos uno.",
      uniqueP1: "La mayoría del café \"personalizado\" te da un cuestionario y elige entre 5 blends existentes. Brewify hace algo que nadie más hace: empieza desde cero, lee cómo estás llegando a la vida ahora mismo, y diseña un blend que solo tiene sentido para ti.",
      uniqueP2: "El resultado tiene un nombre, un tueste, un perfil de sabor y una historia — escrita en el lenguaje de tu momento. Y una vez creado, es tuyo. Permanentemente. En el sitio. Generando cada vez que alguien lo pide.",
      processEyebrow: "El proceso",
      processHeadline: "De tus respuestas a tu taza.",
      steps: [
        { n: "01", title: "Respondes 5 preguntas", body: "Estado de ánimo. Temporada de vida. Cuándo lo tomas. Qué estás construyendo. Qué importa. Simple, honesto, rápido." },
        { n: "02", title: "Diseñamos tu blend", body: "Nuestro modelo traduce tus respuestas en un nivel de tueste, perfil de sabor y una pequeña historia — escrita solo para ti." },
        { n: "03", title: "Se convierte en tuyo", body: "Tu blend recibe un nombre, una etiqueta y un lugar permanente en el sitio. Nadie más tendrá el mismo." },
        { n: "04", title: "Ganas con él", body: "Cada vez que alguien pide tu blend, ganas $1. Úsalo como crédito en la tienda o canjéalo en efectivo desde $100." },
      ],
      farmerEyebrow: "El origen",
      farmerHeadline: "Cada blend comienza en las manos de una familia agricultora.",
      farmerP1: "Nuestros granos provienen de pequeñas granjas familiares en la cuenca amazónica — cultivadores que han pasado generaciones dominando un solo cultivo. No son grandes propiedades industriales. No son cadenas de suministro de productos básicos.",
      farmerP2: "Cuando pides un blend Brewify, el 10% de esa venta va directamente a la familia agricultora cuyos granos lo hicieron posible. No como caridad. Como una parte justa del valor que crearon.",
      farmerP3: "Los 100 miembros fundadores llevan ese compromiso hacia adelante permanentemente — sus blends generan ingresos para los agricultores cada vez que se piden.",
      farmerLocation: "Cuenca amazónica · Brasil",
      valuesEyebrow: "Lo que defendemos",
      valuesHeadline: "Construido diferente. Con propósito.",
      values: [
        { icon: "🌱", title: "Origen amazónico", body: "Cada grano proviene de pequeñas granjas familiares en el interior de la Amazonia. Personas que han pasado generaciones aprendiendo un solo cultivo." },
        { icon: "💰", title: "Ganancias directas para agricultores", body: "El 10% de cada pedido va directamente a la familia agricultora que lo hizo posible. No es una donación — es una parte justa de la venta." },
        { icon: "♻️", title: "Tostado limpio", body: "Tostado en pequeños lotes bajo demanda. Sin sobreproducción, sin inventario envejeciendo. Tu bolsa se tuesta cuando la pides." },
        { icon: "🔒", title: "Sin recetas genéricas", body: "No tenemos catálogo. Cada blend se crea desde cero, para una persona. Nada se repite." },
      ],
      ctaHeadline: "¿Listo para crear el tuyo?",
      ctaSub: "Conviértete en miembro fundador de THE 100 y sé parte de cómo empieza Brewify.",
      ctaPrimary: "Reserva tu lugar — $299",
      ctaSecondary: "Explorar THE 100",
    },
    investor: {
      eyebrow: "Relaciones con Inversores",
      headline: "La industria del café\nno ha cambiado.",
      headlineItalic: "Nosotros la estamos cambiando.",
      subheadline: "Brewify está construyendo la primera marca de café donde cada producto es único, cada cliente es un creador, y cada pedido apoya a quienes cultivan los granos.",
      cta: "Solicitar una conversación",
      metrics: [
        { value: "$200B+", label: "Mercado global del café", sub: "Una de las categorías de consumo diario más grandes del mundo." },
        { value: "0", label: "Jugadores en personalización real", sub: "Ninguna marca ha resuelto café por persona a escala. La categoría está completamente abierta." },
        { value: "94%", label: "Retención vía identidad", sub: "Los productos ligados a la identidad personal retienen clientes a tasas que las marcas masivas no pueden igualar." },
        { value: "3×", label: "LTV vs café commodity", sub: "Los productos personalizados generan mayores márgenes y relaciones más largas con los clientes." },
      ],
      opportunityEyebrow: "La oportunidad",
      opportunityHeadline: "Seis razones por las que el momento es ahora.",
      why: [
        { title: "Brecha de categoría", body: "Ninguna marca ha combinado café personalizado por IA, una capa de economía creativa y abastecimiento directo de agricultores amazónicos en un solo producto." },
        { title: "Recurrencia por diseño", body: "Una vez que alguien crea su blend, lo repide. La conexión personal con un producto nombrado y autorado crea retención que las suscripciones genéricas no pueden igualar." },
        { title: "Lealtad basada en activos", body: "Los 100 miembros no solo se suscriben — poseen algo. Un blend que les genera dinero. Esa es una relación fundamentalmente diferente con una marca." },
        { title: "Ventaja ética", body: "El modelo de abastecimiento amazónico y los pagos directos a agricultores no son texto de marketing — son estructurales. Difícil de copiar. Fácil de contar." },
        { title: "Puente digital-físico", body: "Cada blend vive en línea permanentemente. Puede regalarse, transferirse, pedirse por cualquiera. Es un producto físico con mecánicas de activo digital." },
        { title: "Modelo de tracción temprana", body: "Los 100 miembros fundadores prueban la demanda, financian las operaciones iniciales de tostado y crean la comunidad que comercializa el producto orgánicamente." },
      ],
      visionEyebrow: "La visión",
      visionHeadline: "La fase uno es café.\nLa fase dos es todo lo que personalizas.",
      visionP1: "La tecnología central de Brewify es un motor de personalización que traduce contexto humano — estado de ánimo, temporada de vida, aspiración — en un producto físico. El café es la primera aplicación porque es íntimo, diario y profundamente ligado a la identidad.",
      visionP2: "La tesis a largo plazo es una plataforma: cualquier categoría de producto donde el contexto personal cambia lo que alguien querría. Té. Suplementos. Fragancia. La infraestructura construida para el café aplica en todas partes.",
      visionP3: "No estamos vendiendo bolsas de café. Estamos construyendo infraestructura para bienes físicos personalizados — empezando donde el apego emocional es más profundo.",
      contactEyebrow: "Ponte en contacto",
      contactHeadline: "¿Interesado en invertir?",
      contactSub: "Estamos teniendo conversaciones iniciales con inversores que entienden marca, comunidad y el espacio de bienes de consumo. Si eres tú, nos gustaría hablar.",
      contactEmailLabel: "Correo directo",
      nameLabel: "Nombre",
      emailLabel: "Correo electrónico",
      firmLabel: "Empresa / Organización",
      firmOptional: "(opcional)",
      firmPlaceholder: "Nombre del fondo o empresa",
      namePlaceholder: "Tu nombre",
      emailPlaceholder: "tu@empresa.com",
      messagePlaceholder: "Cuéntanos sobre tu tesis de inversión y qué te atrae de Brewify...",
      messageLabel: "Mensaje",
      sendBtn: "Enviar consulta",
      sending: "Enviando…",
      successTitle: "Mensaje recibido.",
      successSub: "Nos pondremos en contacto en 48 horas.",
      responseNote: "Respondemos a todas las consultas serias en 48 horas.",
    },
    terms: {
      eyebrow: "Legal",
      headline: "Términos de Uso",
      updated: "Última actualización: marzo de 2026",
      sections: [
        { title: "1. Aceptación de Términos", body: "Al acceder o usar Brewify Coffee (Brewify, nosotros), aceptas quedar sujeto a estos Términos de Uso. Si no estás de acuerdo, por favor no uses el sitio ni los servicios." },
        { title: "2. Uso del Sitio", body: "Puedes navegar por Brewify para uso personal y no comercial. Aceptas no copiar, rastrear, revender ni explotar ningún contenido o funcionalidad de la plataforma sin permiso por escrito." },
        { title: "3. Cuentas y Acceso", body: "Algunas funciones — incluidas Crea tu Café y la membresía THE 100 — requieren una cuenta o código de invitación verificado. Eres responsable de mantener la confidencialidad de tus credenciales." },
        { title: "4. Membresía THE 100", body: "Comprar una membresía fundadora te otorga los derechos descritos en la página de Membresía, incluyendo un slot permanente de blend, ganancias sobre pedidos de tu blend y tokens de invitación. Estos derechos no son reembolsables una vez creado el blend. La propiedad del blend puede transferirse a otro usuario." },
        { title: "5. Ganancias y Pagos", body: "Los miembros ganan $1 por bolsa vendida de su blend. Las ganancias pueden aplicarse como crédito en tienda en cualquier momento. Los pagos en efectivo requieren un saldo mínimo de $100 y se procesan mensualmente bajo solicitud." },
        { title: "6. Propiedad Intelectual", body: "Los nombres de blends, historias y perfiles creados a través de Brewify están asociados a tu cuenta pero pueden aparecer públicamente en el sitio. Brewify se reserva el derecho de mostrar tu blend como parte de la plataforma." },
        { title: "7. Conducta Prohibida", body: "Aceptas no: usar la plataforma para ningún propósito ilegal; intentar acceso no autorizado a cualquier parte del sitio; enviar información falsa o engañosa; ni interferir con la seguridad de la plataforma." },
        { title: "8. Limitación de Responsabilidad", body: "Brewify se proporciona tal cual. No somos responsables de ningún daño indirecto, incidental o consecuente derivado del uso de la plataforma, en la medida máxima permitida por la ley." },
        { title: "9. Cambios en los Términos", body: "Podemos actualizar estos Términos en cualquier momento. El uso continuado del sitio después de los cambios constituye la aceptación de los Términos revisados." },
        { title: "10. Contacto", body: "¿Preguntas sobre estos Términos? Escríbenos a iam@brewifycoffee.com." },
      ],
    },
    privacy: {
      eyebrow: "Legal",
      headline: "Política de Privacidad",
      updated: "Última actualización: marzo de 2026",
      sections: [
        { title: "1. Información que Recopilamos", body: "Recopilamos información que proporcionas directamente — como nombre, correo electrónico y respuestas a las preguntas de creación de blend — así como datos técnicos como dirección IP, tipo de navegador y páginas visitadas." },
        { title: "2. Cómo Usamos Tu Información", body: "Usamos tu información para crear y entregar tu blend personalizado, gestionar tu cuenta, enviar correos transaccionales, procesar ganancias y pagos, y mejorar la plataforma. No vendemos tu información personal a terceros." },
        { title: "3. Datos del Blend", body: "Tu perfil de blend — incluidas respuestas, nombre del blend, nivel de tueste y notas de sabor — puede mostrarse públicamente en el sitio si eliges agregar tu blend al feed público. Puedes rechazarlo durante el proceso de creación." },
        { title: "4. Cookies", body: "Usamos cookies esenciales para mantener tu sesión y preferencias (como selección de idioma). No usamos cookies de rastreo o publicidad." },
        { title: "5. Retención de Datos", body: "Conservamos tus datos mientras tu cuenta esté activa o según sea necesario para prestar servicios. Puedes solicitar la eliminación de tus datos en cualquier momento contactándonos." },
        { title: "6. Servicios de Terceros", body: "Usamos Vercel para alojamiento. Tus datos pueden procesarse en servidores en Estados Unidos. No compartimos tus datos personales con redes publicitarias ni intermediarios de datos." },
        { title: "7. Tus Derechos", body: "Según tu ubicación, puedes tener derecho a acceder, corregir, eliminar o restringir el procesamiento de tus datos personales. Para ejercer estos derechos, contáctanos en iam@brewifycoffee.com." },
        { title: "8. Menores", body: "Brewify no está dirigido a menores de 13 años. No recopilamos datos de menores de 13 años de manera intencional." },
        { title: "9. Cambios en Esta Política", body: "Podemos actualizar esta Política de Privacidad periódicamente. Notificaremos a los usuarios registrados sobre cambios importantes por correo electrónico." },
        { title: "10. Contacto", body: "¿Preguntas sobre privacidad? Escríbenos a iam@brewifycoffee.com." },
      ],
    },
    accessibility: {
      eyebrow: "Legal",
      headline: "Declaración de Accesibilidad",
      updated: "Última actualización: marzo de 2026",
      commitmentTitle: "Nuestro Compromiso",
      commitmentBody: "Brewify Coffee está comprometido a hacer nuestro sitio web accesible para todos los usuarios, independientemente de su capacidad o tecnología. Nos esforzamos por cumplir con las Pautas de Accesibilidad para el Contenido Web (WCAG) 2.1, Nivel AA.",
      measuresTitle: "Medidas que Tomamos",
      measures: [
        "HTML semántico para una estructura clara del documento",
        "Razones de contraste de color adecuadas en todos los elementos de texto",
        "Navegabilidad por teclado en todo el sitio",
        "Texto alternativo descriptivo en todas las imágenes significativas",
        "Indicadores de enfoque claros para usuarios de teclado",
        "Diseño responsivo que funciona en distintos tamaños de pantalla y niveles de zoom",
        "Formularios con campos claramente etiquetados y mensajes de error accesibles",
      ],
      limitationsTitle: "Limitaciones Conocidas",
      limitationsBody: "Aunque nos esforzamos por la accesibilidad total, algunos elementos pueden no cumplir aún con todos los criterios WCAG 2.1 AA. Estamos trabajando activamente para identificar y resolver estas brechas.",
      feedbackTitle: "Comentarios y Contacto",
      feedbackBody: "Si experimentas alguna barrera de accesibilidad o tienes comentarios, contáctanos:",
      responseNote: "Buscamos responder a los comentarios de accesibilidad en 3 días hábiles.",
    },
    doNotSell: {
      eyebrow: "Legal",
      headline: "No Vender ni Compartir Mi Información Personal",
      subtitle: "De acuerdo con la Ley de Privacidad del Consumidor de California (CCPA) y regulaciones similares.",
      commitmentTitle: "Nuestro Compromiso",
      commitmentP1: "Brewify Coffee no vende tu información personal a terceros ni la comparte con terceros para publicidad comportamental entre contextos.",
      commitmentP2: "Solo recopilamos lo necesario para operar la plataforma — tu correo, preferencias de blend y actividad de cuenta. Esta información se usa exclusivamente para brindarte nuestro servicio.",
      rightsTitle: "Tus Derechos (CCPA y Leyes Similares)",
      rights: [
        "Saber qué información personal recopilamos y cómo se usa",
        "Solicitar la eliminación de tu información personal",
        "Optar por no vender ni compartir tu información personal",
        "No sufrir discriminación por ejercer tus derechos de privacidad",
      ],
      optOutTitle: "Enviar Solicitud de Exclusión",
      optOutSub: "Ingresa tu correo electrónico para solicitar formalmente que no vendamos ni compartamos tu información personal.",
      emailPlaceholder: "tu@correo.com",
      submitBtn: "Enviar solicitud de exclusión",
      successTitle: "Solicitud recibida.",
      successSub: "Procesaremos tu solicitud en 15 días hábiles.",
      contactTitle: "Contacto",
      contactBody: "Para solicitudes relacionadas con privacidad, también puedes escribirnos directamente a",
    },
  },
} as const;

// ─── Context ───────────────────────────────────────────────────────────────────
export type Translations = (typeof translations)[Language];

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
};

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: translations.en,
});

const STORAGE_KEY = "brewify_lang";

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const stored = localStorage.getItem(STORAGE_KEY) as Language | null;
    if (stored && ["en", "pt", "es"].includes(stored)) {
      setLanguageState(stored);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem(STORAGE_KEY, lang);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}

// Hook for extended translations (new pages)
export function useExt() {
  const { language } = useContext(LanguageContext);
  return extTranslations[language];
}
