"use client";

import { createContext, useContext, useEffect, useState } from "react";

export type Language = "en" | "pt" | "es";

export const LANGUAGES: { code: Language; flag: string; label: string }[] = [
  { code: "en", flag: "🇺🇸", label: "EN" },
  { code: "pt", flag: "🇧🇷", label: "PT" },
  { code: "es", flag: "🇪🇸", label: "ES" },
];

export const translations = {
  en: {
    nav: {
      build: "Build",
      the100: "The 100",
      feed: "Feed",
      membership: "Membership",
      store: "Store",
      dashboard: "Dashboard",
      haveInvite: "Have an invite?",
    },
    home: {
      eyebrow: "Brewify Coffee",
      headline: "Coffee that knows you.",
      subheadline: "One person. One blend. Only yours.",
      cta: "Build your coffee",
      alreadyHaveInvite: "Already have an invite?",
      enterCode: "Enter your code",
      inviteLabel: "Invite code",
      invitePlaceholder: "e.g. BREW-001",
      redeemBtn: "Redeem",
      redeeming: "Redeeming…",
      cancelBtn: "Cancel",
      accessGranted: "Access granted. Taking you in.",
      invalidCode: "Invalid or already redeemed.",
      somethingWrong: "Something went wrong.",
      feature1Title: "Personalized",
      feature1Desc: "Each blend is designed from your mood, rhythm, and season of life.",
      feature2Title: "Sustainable",
      feature2Desc: "Sourced with intention, roasted clean, made to be kept.",
      feature3Title: "Yours",
      feature3Desc: "No stock recipes, no generic bags. A profile that exists only for you.",
      waitlistTitle: "Join the waitlist",
      waitlistSub: "We'll notify you when the next wave opens.",
      waitlistPlaceholder: "Your email",
      waitlistBtn: "Join the waitlist",
      waitlistJoining: "Joining…",
      waitlistSuccess: "You're in. We'll notify you when the next wave opens.",
    },
    membership: {
      eyebrow: "Membership",
      headline: "Founding Access.",
      oneTime: "One-time",
      reserveTitle: "Reserve Access",
      reservePrice: "$189.90",
      reserveSubtitle: "Founding Member — only 100 spots",
      reserveFeatures: [
        "Lifetime access to Brewify",
        "Assigned a permanent number in The 100",
        "Your blend featured on the homepage forever",
        "Earn $1 per bag sold — store credit or cash at $100+",
        "5 invite tokens; friends get 50% off their first blend",
      ],
      spotsRemaining: (n: number) => `${n} spots remaining`,
      comingSoon: "Coming soon — you're on the list",    },
    build: {
      header: "Blend Builder",
      stepOf: (step: number) => `Step ${step} of 6`,
      welcomeBackName: (name: string) => `Welcome back, ${name}. Let's see where your coffee wants to be today.`,
      welcomeBack: "Welcome back. Ready for another batch?",
      step1Q: "How are you feeling today?",
      step1Options: ["Focused", "Calm", "Energized", "Reflective", "Exhausted"],
      step2Q: "What are you building in your life right now?",
      step2Placeholder: "A new role. A slower rhythm. A business that feels like me...",
      step3Q: "What's your current life season?",
      step3Options: ["Starting over", "In the grind", "Finding balance", "Celebrating", "Figuring it out"],
      step4Q: "When do you reach for coffee most?",
      step4Options: ["Early morning ritual", "Midday reset", "Late-night thinker", "Whenever I need to feel like myself"],
      step5Q: "What matters most to you right now?",
      step5Options: ["Clarity", "Creativity", "Connection", "Momentum", "Rest"],
      optionalLabel: "Optional",
      labelPlaceholder: "Name for this blend on the label",
      step6Title: "Your blend, on record.",
      step6Sub: "A profile written from how you're arriving to this moment. This is your Brewify batch.",
      loadingTitle: "Designing your blend...",
      loadingSub: "Reading the small details of your day and folding them into something warm.",
      backBtn: "Back",
      nextBtn: "Next",
      designBtn: "Design My Blend",
      startAnotherBtn: "Start Another",
      profileTitle: "Your profile",
      profileDesc1: "As you move through each question, we're quietly sketching the outline of a blend that should only make sense for you.",
      profileDesc2: "When you're finished, we'll translate that into a single label: a name, a roast, and a small story about the season you're in.",
      inProgressTitle: "In progress",
      inProgressDesc: "Give us a few breaths. We're aligning the cup to the life you described.",
      addToFeedLabel: "Add to public feed?",
      instagramPlaceholder: "@instagram",
      addToFeedBtn: "Add to feed",
      addingFeed: "Adding…",
      addedFeed: "Added to public feed.",
      orderBlendBtn: "Order Your Blend",
      error: "Something went wrong while designing your blend.",
    },
    feed: {
      header: "Blend Archive",
      eyebrow: "Blend Archive",
      headline: "Every blend crafted. Each one unrepeatable.",
      loading: "Loading…",
      empty: "No blends archived yet. Be the first.",
      mostOrdered: "Most ordered",
      orderBtn: "Order this blend →",
    },
    dashboard: {
      header: "Archive",
      headline: "Your blends, in sequence.",
      subheadline: "A small record of how you've been arriving to the cup — seasons, shifts, and quiet pivots. Nothing loud, just a log.",
      roast: "Roast",
      reorderBtn: "Reorder",
      compareTitle: "Compare Blends",
    },
    store: {
      title: "GIFT STORE",
      sub: "Objects for the ritual.",
      comingSoon: "Coming soon",
      inviteTitle: "Get the opening invite.",
      inviteDesc: "Launching the store with The 100. A small first run of objects for the people building this with us.",
      emailPlaceholder: "Email",
      notifyBtn: "Notify me when the store opens",
      notifying: "Joining…",
      notifySuccess: "We'll let you know when the store opens.",
      footer: "Designed for the ritual. Launching with The 100.",
      somethingWrong: "Something went wrong.",
    },
    the100: {
      heroSub: "The founding blends of Brewify Coffee.",
      missionEyebrow: "Why it matters",
      missionTitle: "Every blend begins in the Amazon.",
      missionP1: "The coffee we source comes from small family farms deep in the Amazon basin — generations of cultivators who have spent their lives learning a single crop.",
      missionP2: "Every time a Brewify blend is ordered, a portion of that sale goes directly to the farming family whose beans made it possible. The 100 founding members carry that legacy forward.",
      missionP3: "This is not charity. It is the correct way to do business.",
      stat1Value: "10%",
      stat1Label: "of every order → farming families",
      stat2Value: "100",
      stat2Label: "founding members",
      stat3Value: "1 blend",
      stat3Label: "per person. Forever.",
      earnTitle: "You earn",
      earnP1: "Every time someone orders your blend, you earn $1.",
      earnP2: "Use it as store credit anytime, or cash it out once you hit $100.",
      impactTitle: "You impact",
      impactP1: "10% of each order of your blend goes to the farming family who grew those beans.",
      impactP2: "Your number in The 100 is a permanent contribution to their livelihood.",
      ownTitle: "You own",
      ownP1: "Your blend is an asset. Transfer it. Hold it. Let it earn.",
      ownP2: "Founding spots are limited to 100. There will never be more.",
      archiveEyebrow: "The archive",
      archiveTitle: "Claimed blends. Living on the site. Earning forever.",
      loading: "Loading…",
      spotsRemaining: (n: number) => `${n} spots remaining.`,
      ctaTitle: "Claim your number.",
      ctaSub: "One of 100 founding positions. Never restocked.",
      ctaBtn: "Get founding access — $189.90",
      orders: "orders",
      pts: "earned",
    },
    checkout: {
      eyebrow: "Checkout",
      title: "Coming soon — you're on the list",
      sub: (tier: string) => `We're opening ${tier} soon. You'll hear from us.`,
      back: "Back to membership",
    },
    blend: {
      eyebrow: (id: string) => `Blend ${id}`,
      title: "Order this blend",
      sub: "Checkout for pre-designed blends is coming soon.",
      back: "Back to feed",
    },
    modal: {
      amazonNote: "10% of this blend's orders support farming families in the Amazon.",
      foundingMember: "Founding member",
      crafted: "Crafted",
      blendRevenue: "Blend revenue",
      orders: "orders",
      redeemable: "Use as store credit or redeem as cash at $100+",
      pointValue: "$1 earned per bag sold",
      minRedemption: "Cash redemption available at $100+ earned",
      howEarnings: "How earnings work →",
      earningsExplain: "Every time someone orders your blend, you earn $1. Use it as store credit in the Gift Store anytime — or once you reach $100, request a cash payout directly to your account.",
      currentOwner: "Current owner",
      transferBtn: "Transfer ownership",
      transferPlaceholder: "Enter recipient's @instagram or email",
      confirm: "Confirm",
      confirming: "Transferring…",
      cancel: "Cancel",
      transferWarning: "Ownership transfers are permanent. This blend and its future earnings transfer to the new owner.",
      orderBtn: "Order this blend",
      ordering: "Ordering…",
      earnNote: "When ordered, the creator earns $1.",
      share: "Share",
      close: "Close",
    },
    footer: {
      tagline: "Brewify Coffee",
      domain: "brewifycoffee.com",
    },
  },

  pt: {
    nav: {
      build: "Criar",
      the100: "Os 100",
      feed: "Feed",
      membership: "Assinatura",
      store: "Loja",
      dashboard: "Painel",
      haveInvite: "Tem um convite?",
    },
    home: {
      eyebrow: "Brewify Coffee",
      headline: "Um café que te conhece.",
      subheadline: "Uma pessoa. Um blend. Só seu.",
      cta: "Crie seu café",
      alreadyHaveInvite: "Já tem um convite?",
      enterCode: "Digite seu código",
      inviteLabel: "Código de convite",
      invitePlaceholder: "ex: BREW-001",
      redeemBtn: "Resgatar",
      redeeming: "Resgatando…",
      cancelBtn: "Cancelar",
      accessGranted: "Acesso liberado. Te levando para dentro.",
      invalidCode: "Inválido ou já resgatado.",
      somethingWrong: "Algo deu errado.",
      feature1Title: "Personalizado",
      feature1Desc: "Cada blend é criado a partir do seu humor, ritmo e momento de vida.",
      feature2Title: "Sustentável",
      feature2Desc: "Colhido com intenção, torrado com cuidado, feito para durar.",
      feature3Title: "Seu",
      feature3Desc: "Sem receitas genéricas, sem embalagens padrão. Um perfil que existe só para você.",
      waitlistTitle: "Entre na lista de espera",
      waitlistSub: "Avisaremos quando a próxima leva abrir.",
      waitlistPlaceholder: "Seu e-mail",
      waitlistBtn: "Entrar na lista",
      waitlistJoining: "Entrando…",
      waitlistSuccess: "Você está dentro. Avisaremos quando a próxima leva abrir.",
    },
    membership: {
      eyebrow: "Assinatura",
      headline: "Acesso Fundador.",
      oneTime: "Pagamento único",
      reserveTitle: "Acesso Reserve",
      reservePrice: "$189.90",
      reserveSubtitle: "Membro Fundador — apenas 100 vagas",
      reserveFeatures: [
        "Acesso vitalício ao Brewify",
        "Número permanente atribuído em Os 100",
        "Seu blend em destaque na página inicial para sempre",
        "Ganhe $1 por saco vendido — crédito na loja ou dinheiro a partir de $100",
        "5 tokens de convite; amigos ganham 50% de desconto no primeiro blend",
      ],
      spotsRemaining: (n: number) => `${n} vagas restantes`,
      comingSoon: "Em breve — você está na lista",    },
    build: {
      header: "Criador de Blend",
      stepOf: (step: number) => `Etapa ${step} de 6`,
      welcomeBackName: (name: string) => `Bem-vindo de volta, ${name}. Vamos ver onde seu café quer chegar hoje.`,
      welcomeBack: "Bem-vindo de volta. Pronto para outro lote?",
      step1Q: "Como você está se sentindo hoje?",
      step1Options: ["Focado", "Calmo", "Energizado", "Reflexivo", "Exausto"],
      step2Q: "O que você está construindo na sua vida agora?",
      step2Placeholder: "Um novo papel. Um ritmo mais lento. Um negócio que parece a minha cara...",
      step3Q: "Em que estação da vida você está agora?",
      step3Options: ["Recomeçando", "No ritmo", "Encontrando equilíbrio", "Celebrando", "Descobrindo o caminho"],
      step4Q: "Quando você mais busca o café?",
      step4Options: ["Ritual da manhã cedo", "Pausa do meio-dia", "Pensador da madrugada", "Quando preciso me sentir eu mesmo"],
      step5Q: "O que mais importa para você agora?",
      step5Options: ["Clareza", "Criatividade", "Conexão", "Impulso", "Descanso"],
      optionalLabel: "Opcional",
      labelPlaceholder: "Nome para este blend no rótulo",
      step6Title: "Seu blend, registrado.",
      step6Sub: "Um perfil escrito a partir de como você está chegando a este momento. Este é o seu lote Brewify.",
      loadingTitle: "Criando seu blend...",
      loadingSub: "Lendo os pequenos detalhes do seu dia e transformando-os em algo especial.",
      backBtn: "Voltar",
      nextBtn: "Próximo",
      designBtn: "Criar Meu Blend",
      startAnotherBtn: "Começar Outro",
      profileTitle: "Seu perfil",
      profileDesc1: "À medida que você avança em cada pergunta, estamos desenhando silenciosamente o contorno de um blend que só faz sentido para você.",
      profileDesc2: "Quando terminar, vamos traduzir isso em um único rótulo: um nome, uma torra e uma pequena história sobre a estação em que você está.",
      inProgressTitle: "Em andamento",
      inProgressDesc: "Dê-nos alguns instantes. Estamos alinhando a xícara à vida que você descreveu.",
      addToFeedLabel: "Adicionar ao feed público?",
      instagramPlaceholder: "@instagram",
      addToFeedBtn: "Adicionar ao feed",
      addingFeed: "Adicionando…",
      addedFeed: "Adicionado ao feed público.",
      orderBlendBtn: "Pedir Seu Blend",
      error: "Algo deu errado ao criar seu blend.",
    },
    feed: {
      header: "Arquivo de Blends",
      eyebrow: "Arquivo de Blends",
      headline: "Cada blend criado. Cada um irrepetível.",
      loading: "Carregando…",
      empty: "Nenhum blend arquivado ainda. Seja o primeiro.",
      mostOrdered: "Mais pedido",
      orderBtn: "Pedir este blend →",
    },
    dashboard: {
      header: "Arquivo",
      headline: "Seus blends, em sequência.",
      subheadline: "Um pequeno registro de como você tem chegado à xícara — estações, mudanças e pivôs silenciosos. Nada barulhento, apenas um registro.",
      roast: "Torra",
      reorderBtn: "Pedir novamente",
      compareTitle: "Comparar Blends",
    },
    store: {
      title: "LOJA DE PRESENTES",
      sub: "Objetos para o ritual.",
      comingSoon: "Em breve",
      inviteTitle: "Receba o convite de abertura.",
      inviteDesc: "Lançando a loja com Os 100. Uma primeira tiragem de objetos para as pessoas que estão construindo isso conosco.",
      emailPlaceholder: "E-mail",
      notifyBtn: "Me avise quando a loja abrir",
      notifying: "Entrando…",
      notifySuccess: "Avisaremos quando a loja abrir.",
      footer: "Criado para o ritual. Lançando com Os 100.",
      somethingWrong: "Algo deu errado.",
    },
    the100: {
      heroSub: "Os blends fundadores do Brewify Coffee.",
      missionEyebrow: "Por que isso importa",
      missionTitle: "Cada blend começa na Amazônia.",
      missionP1: "O café que buscamos vem de pequenas fazendas familiares no interior da bacia Amazônica — gerações de cultivadores que dedicaram suas vidas a aprender uma única colheita.",
      missionP2: "Cada vez que um blend Brewify é pedido, uma parte dessa venda vai diretamente para a família de agricultores cujos grãos tornaram isso possível. Os 100 membros fundadores carregam esse legado adiante.",
      missionP3: "Isso não é caridade. É a forma correta de fazer negócios.",
      stat1Value: "10%",
      stat1Label: "de cada pedido → famílias agricultoras",
      stat2Value: "100",
      stat2Label: "membros fundadores",
      stat3Value: "1 blend",
      stat3Label: "por pessoa. Para sempre.",
      earnTitle: "Você ganha",
      earnP1: "Cada vez que alguém pede seu blend, você ganha $1.",
      earnP2: "Use como crédito na loja a qualquer hora, ou resgate em dinheiro ao atingir $100.",
      impactTitle: "Você impacta",
      impactP1: "10% de cada pedido do seu blend vai para a família de agricultores que cultivou esses grãos.",
      impactP2: "Seu número em Os 100 é uma contribuição permanente ao sustento deles.",
      ownTitle: "Você possui",
      ownP1: "Seu blend é um ativo. Transfira. Guarde. Deixe render.",
      ownP2: "As vagas fundadoras são limitadas a 100. Nunca haverá mais.",
      archiveEyebrow: "O arquivo",
      archiveTitle: "Blends reivindicados. Vivos no site. Rendendo para sempre.",
      loading: "Carregando…",
      spotsRemaining: (n: number) => `${n} vagas restantes.`,
      ctaTitle: "Reivindique seu número.",
      ctaSub: "Uma das 100 posições fundadoras. Nunca reabastecida.",
      ctaBtn: "Acesso fundador — $189.90",
      orders: "pedidos",
      pts: "ganhos",
    },
    checkout: {
      eyebrow: "Pagamento",
      title: "Em breve — você está na lista",
      sub: (tier: string) => `Estamos abrindo ${tier} em breve. Você receberá novidades.`,
      back: "Voltar para assinatura",
    },
    blend: {
      eyebrow: (id: string) => `Blend ${id}`,
      title: "Pedir este blend",
      sub: "O pagamento para blends pré-criados chegará em breve.",
      back: "Voltar para o feed",
    },
    modal: {
      amazonNote: "10% dos pedidos deste blend apoiam famílias agricultoras na Amazônia.",
      foundingMember: "Membro fundador",
      crafted: "Criado em",
      blendRevenue: "Receita do blend",
      orders: "pedidos",
      redeemable: "Use como crédito na loja ou resgate em dinheiro a partir de $100",
      pointValue: "$1 ganho por saco vendido",
      minRedemption: "Resgate em dinheiro disponível a partir de $100 ganhos",
      howEarnings: "Como os ganhos funcionam →",
      earningsExplain: "Cada vez que alguém pede seu blend, você ganha $1. Use como crédito na loja a qualquer hora — ou ao atingir $100, solicite um pagamento em dinheiro diretamente na sua conta.",
      currentOwner: "Proprietário atual",
      transferBtn: "Transferir propriedade",
      transferPlaceholder: "Digite o @instagram ou e-mail do destinatário",
      confirm: "Confirmar",
      confirming: "Transferindo…",
      cancel: "Cancelar",
      transferWarning: "As transferências de propriedade são permanentes. Este blend e seus ganhos futuros são transferidos para o novo proprietário.",
      orderBtn: "Pedir este blend",
      ordering: "Pedindo…",
      earnNote: "Quando pedido, o criador ganha $1.",
      share: "Compartilhar",
      close: "Fechar",
    },
    footer: {
      tagline: "Brewify Coffee",
      domain: "brewifycoffee.com",
    },
  },

  es: {
    nav: {
      build: "Crear",
      the100: "Los 100",
      feed: "Feed",
      membership: "Membresía",
      store: "Tienda",
      dashboard: "Panel",
      haveInvite: "¿Tienes invitación?",
    },
    home: {
      eyebrow: "Brewify Coffee",
      headline: "Un café que te conoce.",
      subheadline: "Una persona. Un blend. Solo tuyo.",
      cta: "Crea tu café",
      alreadyHaveInvite: "¿Ya tienes invitación?",
      enterCode: "Ingresa tu código",
      inviteLabel: "Código de invitación",
      invitePlaceholder: "ej: BREW-001",
      redeemBtn: "Canjear",
      redeeming: "Canjeando…",
      cancelBtn: "Cancelar",
      accessGranted: "Acceso concedido. Entrando.",
      invalidCode: "Inválido o ya canjeado.",
      somethingWrong: "Algo salió mal.",
      feature1Title: "Personalizado",
      feature1Desc: "Cada blend se diseña según tu estado de ánimo, ritmo y momento de vida.",
      feature2Title: "Sostenible",
      feature2Desc: "Cosechado con intención, tostado limpio, hecho para perdurar.",
      feature3Title: "Tuyo",
      feature3Desc: "Sin recetas genéricas, sin bolsas estándar. Un perfil que existe solo para ti.",
      waitlistTitle: "Únete a la lista de espera",
      waitlistSub: "Te avisaremos cuando abra la próxima tanda.",
      waitlistPlaceholder: "Tu correo electrónico",
      waitlistBtn: "Unirme a la lista",
      waitlistJoining: "Uniéndome…",
      waitlistSuccess: "Ya estás dentro. Te avisaremos cuando abra la próxima tanda.",
    },
    membership: {
      eyebrow: "Membresía",
      headline: "Acceso Fundador.",
      oneTime: "Pago único",
      reserveTitle: "Acceso Reserve",
      reservePrice: "$189.90",
      reserveSubtitle: "Miembro Fundador — solo 100 lugares",
      reserveFeatures: [
        "Acceso de por vida a Brewify",
        "Número permanente asignado en Los 100",
        "Tu blend destacado en la página principal para siempre",
        "Gana $1 por bolsa vendida — crédito en tienda o efectivo desde $100",
        "5 tokens de invitación; los amigos obtienen 50% de descuento en su primer blend",
      ],
      spotsRemaining: (n: number) => `${n} lugares restantes`,
      comingSoon: "Próximamente — ya estás en la lista",    },
    build: {
      header: "Creador de Blend",
      stepOf: (step: number) => `Paso ${step} de 6`,
      welcomeBackName: (name: string) => `Bienvenido de nuevo, ${name}. Veamos dónde quiere estar tu café hoy.`,
      welcomeBack: "Bienvenido de nuevo. ¿Listo para otro lote?",
      step1Q: "¿Cómo te sientes hoy?",
      step1Options: ["Enfocado", "Tranquilo", "Energizado", "Reflexivo", "Agotado"],
      step2Q: "¿Qué estás construyendo en tu vida ahora mismo?",
      step2Placeholder: "Un nuevo rol. Un ritmo más tranquilo. Un negocio que se siente como yo...",
      step3Q: "¿En qué temporada de vida estás ahora?",
      step3Options: ["Empezando de nuevo", "En la rutina", "Encontrando equilibrio", "Celebrando", "Descubriendo el camino"],
      step4Q: "¿Cuándo recurres más al café?",
      step4Options: ["Ritual de madrugada", "Pausa del mediodía", "Pensador nocturno", "Cuando necesito sentirme yo mismo"],
      step5Q: "¿Qué es lo más importante para ti ahora?",
      step5Options: ["Claridad", "Creatividad", "Conexión", "Impulso", "Descanso"],
      optionalLabel: "Opcional",
      labelPlaceholder: "Nombre para este blend en la etiqueta",
      step6Title: "Tu blend, registrado.",
      step6Sub: "Un perfil escrito desde cómo llegas a este momento. Este es tu lote Brewify.",
      loadingTitle: "Diseñando tu blend...",
      loadingSub: "Leyendo los pequeños detalles de tu día y convirtiéndolos en algo especial.",
      backBtn: "Atrás",
      nextBtn: "Siguiente",
      designBtn: "Diseñar Mi Blend",
      startAnotherBtn: "Empezar Otro",
      profileTitle: "Tu perfil",
      profileDesc1: "A medida que avanzas en cada pregunta, estamos esbozando silenciosamente el contorno de un blend que solo tiene sentido para ti.",
      profileDesc2: "Cuando termines, lo traduciremos en una sola etiqueta: un nombre, un tueste y una pequeña historia sobre la temporada en la que estás.",
      inProgressTitle: "En progreso",
      inProgressDesc: "Danos unos momentos. Estamos alineando la taza con la vida que describiste.",
      addToFeedLabel: "¿Agregar al feed público?",
      instagramPlaceholder: "@instagram",
      addToFeedBtn: "Agregar al feed",
      addingFeed: "Agregando…",
      addedFeed: "Agregado al feed público.",
      orderBlendBtn: "Pedir Tu Blend",
      error: "Algo salió mal al diseñar tu blend.",
    },
    feed: {
      header: "Archivo de Blends",
      eyebrow: "Archivo de Blends",
      headline: "Cada blend creado. Cada uno irrepetible.",
      loading: "Cargando…",
      empty: "Aún no hay blends archivados. Sé el primero.",
      mostOrdered: "Más pedido",
      orderBtn: "Pedir este blend →",
    },
    dashboard: {
      header: "Archivo",
      headline: "Tus blends, en secuencia.",
      subheadline: "Un pequeño registro de cómo has llegado a la taza — temporadas, cambios y giros silenciosos. Nada ruidoso, solo un registro.",
      roast: "Tueste",
      reorderBtn: "Volver a pedir",
      compareTitle: "Comparar Blends",
    },
    store: {
      title: "TIENDA DE REGALOS",
      sub: "Objetos para el ritual.",
      comingSoon: "Próximamente",
      inviteTitle: "Recibe la invitación de apertura.",
      inviteDesc: "Lanzando la tienda con Los 100. Una primera tirada de objetos para las personas que construyen esto con nosotros.",
      emailPlaceholder: "Correo electrónico",
      notifyBtn: "Avísame cuando abra la tienda",
      notifying: "Uniéndome…",
      notifySuccess: "Te avisaremos cuando abra la tienda.",
      footer: "Diseñado para el ritual. Lanzando con Los 100.",
      somethingWrong: "Algo salió mal.",
    },
    the100: {
      heroSub: "Los blends fundadores de Brewify Coffee.",
      missionEyebrow: "Por qué importa",
      missionTitle: "Cada blend comienza en el Amazonas.",
      missionP1: "El café que obtenemos proviene de pequeñas granjas familiares en lo profundo de la cuenca amazónica — generaciones de cultivadores que han dedicado sus vidas a aprender un solo cultivo.",
      missionP2: "Cada vez que se pide un blend Brewify, una parte de esa venta va directamente a la familia agricultora cuyos granos lo hicieron posible. Los 100 miembros fundadores llevan ese legado hacia adelante.",
      missionP3: "Esto no es caridad. Es la forma correcta de hacer negocios.",
      stat1Value: "10%",
      stat1Label: "de cada pedido → familias agricultoras",
      stat2Value: "100",
      stat2Label: "miembros fundadores",
      stat3Value: "1 blend",
      stat3Label: "por persona. Para siempre.",
      earnTitle: "Ganas",
      earnP1: "Cada vez que alguien pide tu blend, ganas $1.",
      earnP2: "Úsalo como crédito en la tienda cuando quieras, o canjéalo en efectivo al llegar a $100.",
      impactTitle: "Impactas",
      impactP1: "El 10% de cada pedido de tu blend va a la familia agricultora que cultivó esos granos.",
      impactP2: "Tu número en Los 100 es una contribución permanente a su sustento.",
      ownTitle: "Posees",
      ownP1: "Tu blend es un activo. Transfierelo. Consérvalo. Déjalo rendir.",
      ownP2: "Los lugares fundadores están limitados a 100. Nunca habrá más.",
      archiveEyebrow: "El archivo",
      archiveTitle: "Blends reclamados. Vivos en el sitio. Generando para siempre.",
      loading: "Cargando…",
      spotsRemaining: (n: number) => `${n} lugares restantes.`,
      ctaTitle: "Reclama tu número.",
      ctaSub: "Una de las 100 posiciones fundadoras. Nunca reabastecida.",
      ctaBtn: "Acceso fundador — $189.90",
      orders: "pedidos",
      pts: "ganados",
    },
    checkout: {
      eyebrow: "Pago",
      title: "Próximamente — ya estás en la lista",
      sub: (tier: string) => `Estamos abriendo ${tier} pronto. Te avisaremos.`,
      back: "Volver a membresía",
    },
    blend: {
      eyebrow: (id: string) => `Blend ${id}`,
      title: "Pedir este blend",
      sub: "El pago para blends prediseñados llegará pronto.",
      back: "Volver al feed",
    },
    modal: {
      amazonNote: "El 10% de los pedidos de este blend apoya a familias agricultoras en el Amazonas.",
      foundingMember: "Miembro fundador",
      crafted: "Creado el",
      blendRevenue: "Ingresos del blend",
      orders: "pedidos",
      redeemable: "Úsalo como crédito en la tienda o canjéalo en efectivo a partir de $100",
      pointValue: "$1 ganado por bolsa vendida",
      minRedemption: "Canje en efectivo disponible desde $100 ganados",
      howEarnings: "Cómo funcionan las ganancias →",
      earningsExplain: "Cada vez que alguien pide tu blend, ganas $1. Úsalo como crédito en la Tienda de Regalos cuando quieras — o cuando llegues a $100, solicita un pago en efectivo directo a tu cuenta.",
      currentOwner: "Propietario actual",
      transferBtn: "Transferir propiedad",
      transferPlaceholder: "Ingresa el @instagram o correo del destinatario",
      confirm: "Confirmar",
      confirming: "Transfiriendo…",
      cancel: "Cancelar",
      transferWarning: "Las transferencias de propiedad son permanentes. Este blend y sus ganancias futuras se transfieren al nuevo propietario.",
      orderBtn: "Pedir este blend",
      ordering: "Pidiendo…",
      earnNote: "Cuando se pide, el creador gana $1.",
      share: "Compartir",
      close: "Cerrar",
    },
    footer: {
      tagline: "Brewify Coffee",
      domain: "brewifycoffee.com",
    },
  },
} as const;

// ─── Context ───────────────────────────────────────────────────────────────────
export type Translations = (typeof translations)[Language];

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
};

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: translations.en,
});

const STORAGE_KEY = "brewify_lang";

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const stored = localStorage.getItem(STORAGE_KEY) as Language | null;
    if (stored && ["en", "pt", "es"].includes(stored)) {
      setLanguageState(stored);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem(STORAGE_KEY, lang);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
